### PR TITLE
Add entities.Location.update()

### PR DESCRIPTION
**Pull request by abalakh**
Added ```entities.Location.update()```, as it's needed for SatelliteQE/robottelo#2427 .
Also updated tests and submitted [BZ1236008](https://bugzilla.redhat.com/show_bug.cgi?id=1236008).

### CODE REVIEW

**Comment by Ichimonji10** [comment]
Part of #111.

**Comment by Ichimonji10** [comment]
Nice job! :100: ACK

**Comment by abalakh** [comment]
Rebased

**Comment by omaciel** [comment]
ACK

**Comment by elyezer** [comment]
:+1:

**Pull request merged**
