### PR TITLE
fixes #658 - Add scap_content_profiles field in ScapContents.

### LINKED ISSUE #658: Add scap_content_profiles field in ScapContents.
scap_content_profiles field is not present in ScapContents entity.
Reference: [https://github.com/SatelliteQE/nailgun/pull/653](https://github.com/SatelliteQE/nailgun/pull/653)

### PR DESCRIPTION
**Pull request by jameerpathan111**
Fixes #658

### CODE REVIEW

**Comment by ntkathole** [comment]
ok to test : tests/foreman/longrun/test_oscap.py -k test_positive_push_updated_content

**Comment by jameerpathan111** [comment]
API test results:

```
In [4]:  entities.ScapContents(id=3).read()                                                                                                                                                
Out[4]: nailgun.entities.ScapContents(title='Red Hat rhel6 default content updated', original_filename='ssg-rhel6-ds.xml', location=[nailgun.entities.Location(id=2)], organization=[nailgun.entities.Organization(id=1)], scap_content_profiles=[{'id': 3, 'profile_id': 'xccdf_org.ssgproject.content_profile_pci-dss', 'title': 'PCI-DSS v3 Control Baseline for Red Hat Enterprise Linux 6'}, {'id': 4, 'profile_id': 'xccdf_org.ssgproject.content_profile_rht-ccp', 'title': 'Red Hat Corporate Profile for Certified Cloud Providers (RH CCP)'}, {'id': 5, 'profile_id': 'xccdf_org.ssgproject.content_profile_C2S', 'title': 'C2S for Red Hat Enterprise Linux 6'}, {'id': 6, 'profile_id': 'xccdf_org.ssgproject.content_profile_server', 'title': 'Server Baseline'}, {'id': 7, 'profile_id': 'xccdf_org.ssgproject.content_profile_CSCF-RHEL6-MLS', 'title': 'CSCF RHEL6 MLS Core Baseline'}, {'id': 8, 'profile_id': 'xccdf_org.ssgproject.content_profile_stig-rhel6-disa', 'title': 'DISA STIG for Red Hat Enterprise Linux 6'}, {'id': 9, 'profile_id': 'xccdf_org.ssgproject.content_profile_CS2', 'title': 'Example Server Profile'}, {'id': 10, 'profile_id': 'xccdf_org.ssgproject.content_profile_standard', 'title': 'Standard System Security Profile for Red Hat Enterprise Linux 6'}, {'id': 11, 'profile_id': 'xccdf_org.ssgproject.content_profile_ftp-server', 'title': 'FTP Server Profile (vsftpd)'}, {'id': 12, 'profile_id': 'xccdf_org.ssgproject.content_profile_fisma-medium-rhel6-server', 'title': 'FISMA Medium for Red Hat Enterprise Linux 6'}, {'id': 13, 'profile_id': 'xccdf_org.ssgproject.content_profile_desktop', 'title': 'Desktop Baseline'}, {'id': 14, 'profile_id': 'xccdf_org.ssgproject.content_profile_nist-CL-IL-AL', 'title': 'CNSSI 1253 Low/Low/Low Control Baseline'}, {'id': 15, 'profile_id': 'xccdf_org.ssgproject.content_profile_usgcb-rhel6-server', 'title': 'United States Government Configuration Baseline (USGCB)'}], id=3)

In [5]: sc1 = entities.ScapContents(id=3, title='Red Hat rhel6 default content updated').update()                                                                                          

In [6]: sc1                                                                                                                                                                                
Out[6]: nailgun.entities.ScapContents(title='Red Hat rhel6 default content updated', original_filename='ssg-rhel6-ds.xml', location=[nailgun.entities.Location(id=2)], organization=[nailgun.entities.Organization(id=1)], scap_content_profiles=[{'id': 3, 'profile_id': 'xccdf_org.ssgproject.content_profile_pci-dss', 'title': 'PCI-DSS v3 Control Baseline for Red Hat Enterprise Linux 6'}, {'id': 4, 'profile_id': 'xccdf_org.ssgproject.content_profile_rht-ccp', 'title': 'Red Hat Corporate Profile for Certified Cloud Providers (RH CCP)'}, {'id': 5, 'profile_id': 'xccdf_org.ssgproject.content_profile_C2S', 'title': 'C2S for Red Hat Enterprise Linux 6'}, {'id': 6, 'profile_id': 'xccdf_org.ssgproject.content_profile_server', 'title': 'Server Baseline'}, {'id': 7, 'profile_id': 'xccdf_org.ssgproject.content_profile_CSCF-RHEL6-MLS', 'title': 'CSCF RHEL6 MLS Core Baseline'}, {'id': 8, 'profile_id': 'xccdf_org.ssgproject.content_profile_stig-rhel6-disa', 'title': 'DISA STIG for Red Hat Enterprise Linux 6'}, {'id': 9, 'profile_id': 'xccdf_org.ssgproject.content_profile_CS2', 'title': 'Example Server Profile'}, {'id': 10, 'profile_id': 'xccdf_org.ssgproject.content_profile_standard', 'title': 'Standard System Security Profile for Red Hat Enterprise Linux 6'}, {'id': 11, 'profile_id': 'xccdf_org.ssgproject.content_profile_ftp-server', 'title': 'FTP Server Profile (vsftpd)'}, {'id': 12, 'profile_id': 'xccdf_org.ssgproject.content_profile_fisma-medium-rhel6-server', 'title': 'FISMA Medium for Red Hat Enterprise Linux 6'}, {'id': 13, 'profile_id': 'xccdf_org.ssgproject.content_profile_desktop', 'title': 'Desktop Baseline'}, {'id': 14, 'profile_id': 'xccdf_org.ssgproject.content_profile_nist-CL-IL-AL', 'title': 'CNSSI 1253 Low/Low/Low Control Baseline'}, {'id': 15, 'profile_id': 'xccdf_org.ssgproject.content_profile_usgcb-rhel6-server', 'title': 'United States Government Configuration Baseline (USGCB)'}], id=3)

In [7]: entities.ScapContents().search()                                                                                                                                                   
Out[7]: 
[nailgun.entities.ScapContents(title='Red Hat firefox default content', original_filename='ssg-firefox-ds.xml', location=[nailgun.entities.Location(id=2)], organization=[nailgun.entities.Organization(id=1)], id=1),
 nailgun.entities.ScapContents(title='Red Hat jre default content', original_filename='ssg-jre-ds.xml', location=[nailgun.entities.Location(id=2)], organization=[nailgun.entities.Organization(id=1)], id=2),
 nailgun.entities.ScapContents(title='Red Hat rhel6 default content updated', original_filename='ssg-rhel6-ds.xml', location=[nailgun.entities.Location(id=2)], organization=[nailgun.entities.Organization(id=1)], id=3),
 nailgun.entities.ScapContents(title='Red Hat rhel7 default content', original_filename='ssg-rhel7-ds.xml', location=[nailgun.entities.Location(id=2)], organization=[nailgun.entities.Organization(id=1)], id=4)]
```

**Comment by jameerpathan111** [comment]
ok to test : tests/foreman/longrun/test_oscap.py -k test_positive_push_updated_content

**Comment by jameerpathan111** [comment]
Build 87 of nailgun-reviewer is completed successfully with no error or test failures.

**Pull request merged**
