### PR TITLE
Fix read() of hostgroup without content_source, lce or cv for sat6.1

### LINKED ISSUE #279: Cannot read hostgroups without content_source, content_view or lifecycle_environment
When trying to run read() on a hostgroup that doesn't have the $subject properties set (Such hostgroup could easily be created from the UI), the following exception is yielded:

```
.../python2.7/site-packages/nailgun/entities.pyc in read(self, entity, attrs, ignore)
   1964                          'content_view_id',
   1965                          'lifecycle_environment_id'):
-> 1966                 attrs[attr] = attrs2[attr]
   1967         return super(HostGroup, self).read(entity, attrs, ignore)
   1968 

KeyError: 'content_source_id'
```

### PR DESCRIPTION
**Pull request by abalakh**
Resolves #279 
Issue is pretty old, i'd even think of removing such workaround, but just in case somebody is using sat6.1 with latest nailgun - fix is very trivial.

### CODE REVIEW

**Comment by oshtaier** [comment]
ACK pending any test result for at least 6.3, but 6.1 will be also pretty good

**Comment by abalakh** [comment]
@oshtaier the change is inside a block for 6.1 only, there's no point in 6.3 results here (except of syntax error maybe, which is not the case).

**Comment by abalakh** [comment]
Sat 6.1:
```python
>>> from nailgun import config, entities
>>> cfg = config.ServerConfig('https://example1.redhat.com', version='6.1.0', auth=('admin', 'secretpassword'), verify=False)
>>> hg = entities.HostGroup(cfg).create(True)
>>> hg.read()
nailgun.entities.HostGroup(nailgun.config.ServerConfig(url='https://example1.redhat.com', verify=False, version='6.1.0', auth=('admin', 'secretpassword')), domain=None, medium=None, parent=None, ptable=None, content_source=None, lifecycle_environment=None, operatingsystem=None, name=u'mFrpqpUPkHFT', subnet=None, puppet_proxy=None, realm=None, content_view=None, id=1, environment=None, location=[], organization=[], puppet_ca_proxy=None, architecture=None)
```
Sat 6.3:
```python
>>> cfg630 = config.ServerConfig('https://example2.redhat.com', version='6.3.0', auth=('admin', 'secretpassword'), verify=False)
>>> hg = entities.HostGroup(cfg630).create(True)
>>> hg.read()
nailgun.entities.HostGroup(nailgun.config.ServerConfig(url='https://example2.redhat.com', verify=False, version='6.3.0', auth=('admin', 'secretpassword')), domain=None, medium=None, parent=None, ptable=None, content_source=None, lifecycle_environment=None, operatingsystem=None, name=u'iZIbMEIldFM', subnet=None, puppet_proxy=None, realm=None, content_view=None, id=1, environment=None, location=[], organization=[], puppet_ca_proxy=None, architecture=None)
```

**Comment by oshtaier** [comment]
ACK

**Pull request merged**
