### PR TITLE
Improve _handle_response

### PR DESCRIPTION
**Pull request by elyezer**
Check for presence of `application/json` on response headers instead
equality since on the header value the charset can be specified, like
`application/json; charset=utf-8`.

### CODE REVIEW

**Comment by oshtaier** [comment]
ACK pending fix for unit tests and 1 random test results

**Comment by oshtaier** [comment]
Thanks @elyezer and @sthirugn for finding root cause and sorry for introduced regression

**Comment by Ichimonji10** [comment]
ACK

**Comment by elyezer** [comment]
```
py.test --pdb tests/foreman/api/test_docker.py -k test_create_container_compute_resource_power
======================= test session starts =======================
platform linux2 -- Python 2.7.10 -- py-1.4.30 -- pytest-2.7.2
rootdir: /home/elyezer/code/robottelo, inifile: 
plugins: cov
collected 44 items 

tests/foreman/api/test_docker.py .

 43 tests deselected by '-ktest_create_container_compute_resource_power' 
============ 1 passed, 43 deselected in 57.12 seconds =============
```

**Comment by elyezer** [comment]
Ran the automation for RHEL6.7 and got no errors on API!

**Comment by sthirugn** [comment]
:+1:

**Comment by omaciel** [comment]
Rock!

**Comment by Ichimonji10** [comment]
Woohoo!

**Pull request merged**
