### PR TITLE
Update "examples" section in documentation

### PR DESCRIPTION
**Pull request by Ichimonji10**
* Add table of contents where appropriate.
* Place the video introduction in to its own section.
* Explain how it is possible to call `create()`, `read()`, etc on both brand new
  and existing objects.

### CODE REVIEW

**Comment by Ichimonji10** [comment]
@abalakh @oshtaier

**Comment by elyezer** [comment]
ACK

**Comment by abalakh** [comment]
ACK

**Comment by oshtaier** [comment]
ACK

**Pull request merged**
