### PR TITLE
Adding two more fields for partition table entity

### PR DESCRIPTION
**Pull request by oshtaier**
Adding location and organization fields to Partition Table entity
Please refer to https://bugzilla.redhat.com/show_bug.cgi?id=1320459 for more details
```
>>> test = entities.PartitionTable(organization=[1]).create(True)
>>> test
nailgun.entities.PartitionTable(nailgun.config.ServerConfig(url=u'https://server', verify=False, auth=(u'admin', u'changeme')), layout=u'\u7abf\ufc1c\U00029f67\U00020d89\u7cbb\u0178\U00023182\U000210be\ua20d\U00022c5e\U0002766f\ucb75\U00010008\ubb7d\U00023153\U00022bbe\ufeaa\u857e\U000290e5\u5a17\U00022e79\U0002630e\u5099\U0002a0c1', os_family=None, location=[], organization=[nailgun.entities.Organization(nailgun.config.ServerConfig(url=u'https://server', verify=False, auth=(u'admin', u'changeme')), id=1)], id=198, name=u'\U0002008b\U0002821d\u9789\U00029f91\U00010912\U000208a4\U0002b0d4\u8ec6\ua553\u3b79\ub1d4')
>>> test = entities.PartitionTable(location=[1]).create(True)
>>> test
nailgun.entities.PartitionTable(nailgun.config.ServerConfig(url=u'https://server', verify=False, auth=(u'admin', u'changeme')), layout=u'\U00020c2d\U00026e3d\u98cc\u8e31\U0002823e\U00022cba\u6015', os_family=None, location=[nailgun.entities.Location(nailgun.config.ServerConfig(url=u'https://server', verify=False, auth=(u'admin', u'changeme')), id=1)], organization=[nailgun.entities.Organization(nailgun.config.ServerConfig(url=u'https://server', verify=False, auth=(u'admin', u'changeme')), id=1)], id=199, name=u'\u3f06\U00026ea4\U00025cf9\U00027abe\u1760\u7bac\U00020aa2\ubd69\u6a04\u93d7\U00026977\U00021b11\u3658\u48c6\u37fe\U000259f5\u53e3\U00010b26\U0002a27c\U00023226\U000203c8\U0001305d\U00022706\U00025413\U00027116\u66ae')
```

### CODE REVIEW

**Comment by abalakh** [comment]
Is your change compatible with sat<6.2? I mean were these fields present before?

**Comment by oshtaier** [comment]
Nope, it doesn't
It becomes harder and harder to use these conditions and, honestly, I am not sure about any sensible way to use it inside of `create_missing` method

**Comment by abalakh** [comment]
@oshtaier theoretically, it should be pretty simple, like this:
```python
        if _get_version(self._server_config) >= Version('6.2'):
            self.ptable = PartitionTable(
                 self._server_config,
                 location=[self.location],
                 organization=[self.organization],
             ).create(True)
        else:
            self.ptable = PartitionTable(self._server_config).create(True)
```
The thing is currently we don't specify satellite version when initializing default server config in robottelo. Because of that, `_get_version(self._server_config)` returns version '1.0' and this check will always fail.
I can see 2 ways of solving this:
1) If we can determine which version of sat we are using - update robottelo [here](https://github.com/SatelliteQE/robottelo/blob/master/robottelo/config/settings.py#L729) by adding `version` parameter
2) As the default supported version is the latest one (sat6.2), we can update default value, returned by `_get_version()` [here](https://github.com/SatelliteQE/nailgun/blob/master/nailgun/entities.py#L190) to '6.2'. This makes some sense, as in other words it will sound like 'use the latest code without any workarounds if the opposite wasn't asked' (right now by default we apply all the possible workarounds as '1.0' is definitely less than '6.1' or '6.2').

**Comment by abalakh** [comment]
Or, actually, let me fill a separate issue for that

**Comment by sthirugn** [comment]
ACK pending @abalakh's question.

**Comment by oshtaier** [comment]
Addressed all comments. Going create separate issue for unit tests
6.2 is re-tested and works properly
6.1 is confirmed by @abalakh

**Comment by abalakh** [comment]
ACK

**Comment by abalakh** [comment]
Created #271 for missing unit tests

**Pull request merged**
