### PR TITLE
Support Usergroup as a value for entities.Host.owner field

### LINKED ISSUE #258: Support Usergroup as a value for entities.Host.owner field
Right now the `owner` field for Host entity is defined as
`'owner': entity_fields.OneToOneField(User),`
The issue here is `owner` depends on `owner_type` field, which can be one of 'User' or 'Usergroup'.
In case `owner_type == 'Usergroup`, the host can't be read/created, as nailgun will search for user, not for Usergroup.

### PR DESCRIPTION
**Pull request by abalakh**
`owner` field for Host entity is defined as `'owner': entity_fields.OneToOneField(User)`,
But  `owner` depends on `owner_type` field, which can be one of 'User' or 'Usergroup'.
In case `owner_type == 'Usergroup'`, the host couldn't be read/created, as nailgun was searching for User, not for Usergroup. PR resolves this issue.
Closes #258

### CODE REVIEW

**Comment by abalakh** [comment]
`[WIP]` as i'd like to hear some feedback regarding selected approach, it doesn't look polished enough for me. Also i'll add some unit tests as soon as the solution gets approved.

**Comment by abalakh** [comment]
Test results for both `owner_type == 'User'` and `owner_type == 'Usergroup'` (with tests added in SatelliteQE/robottelo#3298):
```python
py.test tests/foreman/api/test_host.py -k 'test_positive_create_with_user or test_positive_update_user'       
================================ test session starts =================================
platform linux2 -- Python 2.7.10, pytest-2.8.7, py-1.4.31, pluggy-0.3.1
rootdir: /home/andrii/workspace/robottelo, inifile: 
plugins: xdist-1.13.1, repeat-0.2
collected 45 items 

tests/foreman/api/test_host.py ....

 41 tests deselected by '-ktest_positive_create_with_user or test_positive_update_user' 
===================== 4 passed, 41 deselected in 113.78 seconds ======================
```

**Comment by Ichimonji10** [comment]
I played around a bit and the following diff seemed to produce sane results. Can you try it out?

```diff
diff --git a/nailgun/entities.py b/nailgun/entities.py
index 06d232d..570574c 100644
--- a/nailgun/entities.py
+++ b/nailgun/entities.py
@@ -2033,9 +2033,59 @@ class Host(  # pylint:disable=too-many-instance-attributes
             'root_pass': entity_fields.StringField(length=(8, 30)),
             'subnet': entity_fields.OneToOneField(Subnet),
         }
+        self._owner_type = None  # actual ``owner_type`` value
         self._meta = {'api_path': 'api/v2/hosts', 'server_modes': ('sat')}
         super(Host, self).__init__(server_config, **kwargs)
 
+    @property
+    def owner_type(self):
+        """A property that acts like a typical field.
+
+        Normally, NailGun will only set a field if there is a value to assign
+        to it. For example, if one creates a ``Host`` and does not give it a
+        name, then calling ``Host.name`` will raise an ``AttributeError``. This
+        property attempts to emulate that behaviour, by raising an
+        ``AttributeError`` if ``_owner_type is None``. This should work, as
+        ``None`` is not a semantically valid value for this field.
+        """
+        if self._owner_type is None:
+            raise AttributeError(
+                "'{}' object has no attribute 'owner_type'"
+                .format(type(self).__name__)
+            )
+        return self._owner_type
+
+    @owner_type.setter
+    def owner_type(self, value):
+        """Set ``owner_type`` to the given value.
+
+        In addition:
+
+        * Update the internal type of the ``owner`` field.
+        * Update the value of the ``owner`` field if a value is already set.
+        """
+        self._owner_type = value
+        if value == 'User':
+            self._fields['owner'] = entity_fields.OneToOneField(User)
+            if hasattr(self, 'owner'):
+                # pylint:disable=no-member
+                self.owner = User(self._server_config, id=self.owner.id)
+        elif value == 'Usergroup':
+            self._fields['owner'] = entity_fields.OneToOneField(UserGroup)
+            if hasattr(self, 'owner'):
+                # pylint:disable=no-member
+                self.owner = UserGroup(self._server_config, id=self.owner.id)
+
+    def get_values(self):
+        """Correctly set the ``owner_type`` attribute."""
+        attrs = super(Host, self).get_values()
+        attrs['owner_type'] = attrs.pop('_owner_type')
+        if attrs['owner_type'] is None:
+            # If the owner_type attribute has not been set, don't include it in
+            # this response. See owner_type() docstring for details.
+            del attrs['owner_type']
+        return attrs
+
     def create_missing(self):
         """Create a bogus managed host.
```

**Comment by Ichimonji10** [comment]
One more time around. Is this the kind of behaviour we're looking for?

```python
>>> from nailgun import entities
>>>
>>> host = entities.Host(owner=entities.UserGroup(id=10), owner_type='Usergroup')
>>> type(host.owner)
<class 'nailgun.entities.UserGroup'>
>>> type(host.get_values()['owner'])
<class 'nailgun.entities.UserGroup'>
>>> host.owner.id
10
>>>
>>> host = entities.Host(owner_type='Usergroup', owner=entities.UserGroup(id=10))
>>> type(host.owner)
<class 'nailgun.entities.UserGroup'>
>>> type(host.get_values()['owner'])
<class 'nailgun.entities.UserGroup'>
>>> host.owner.id
10
>>>
>>> host = entities.Host(owner=entities.User(id=10), owner_type='User')
>>> type(host.owner)
<class 'nailgun.entities.User'>
>>> type(host.get_values()['owner'])
<class 'nailgun.entities.User'>
>>> host.owner.id
10
>>>
>>> host = entities.Host(owner_type='User', owner=entities.User(id=10))
>>> type(host.owner)
<class 'nailgun.entities.User'>
>>> type(host.get_values()['owner'])
<class 'nailgun.entities.User'>
>>> host.owner.id
10
```

This diff gives said behaviour:

```diff
diff --git a/nailgun/entities.py b/nailgun/entities.py
index 06d232d..a176c30 100644
--- a/nailgun/entities.py
+++ b/nailgun/entities.py
@@ -2033,9 +2033,49 @@ class Host(  # pylint:disable=too-many-instance-attributes
             'root_pass': entity_fields.StringField(length=(8, 30)),
             'subnet': entity_fields.OneToOneField(Subnet),
         }
+        self._owner_type = None  # actual ``owner_type`` value
         self._meta = {'api_path': 'api/v2/hosts', 'server_modes': ('sat')}
         super(Host, self).__init__(server_config, **kwargs)
 
+        # See https://github.com/SatelliteQE/nailgun/issues/258
+        if (
+                hasattr(self, 'owner') and
+                hasattr(self.owner, 'id') and
+                isinstance(self.owner.id, Entity)):
+            self.owner = self.owner.id
+
+    @property
+    def owner_type(self):
+        """Return ``_owner_type``."""
+        return self._owner_type
+
+    @owner_type.setter
+    def owner_type(self, value):
+        """Set ``owner_type`` to the given value.
+
+        In addition:
+
+        * Update the internal type of the ``owner`` field.
+        * Update the value of the ``owner`` field if a value is already set.
+        """
+        self._owner_type = value
+        if value == 'User':
+            self._fields['owner'] = entity_fields.OneToOneField(User)
+            if hasattr(self, 'owner'):
+                # pylint:disable=no-member
+                self.owner = User(self._server_config, id=self.owner.id)
+        elif value == 'Usergroup':
+            self._fields['owner'] = entity_fields.OneToOneField(UserGroup)
+            if hasattr(self, 'owner'):
+                # pylint:disable=no-member
+                self.owner = UserGroup(self._server_config, id=self.owner.id)
+
+    def get_values(self):
+        """Correctly set the ``owner_type`` attribute."""
+        attrs = super(Host, self).get_values()
+        attrs['owner_type'] = attrs.pop('_owner_type')
+        return attrs
+
     def create_missing(self):
         """Create a bogus managed host.
```

**Comment by abalakh** [comment]
@Ichimonji10 the last version seems ok. I've just changed 1 line from
```python
self.owner = User(self._server_config, id=self.owner.id)
```
to
```python
self.owner = User(
    self._server_config,
    id=self.owner.id if isinstance(self.owner, Entity)
    else self.owner
)
```
and for Usergroup accordingly to support integer values, not just entities.

The only thing i'm not sure about - default `Host().update_payload()` now looks like this `{'host': {'owner_type': None}}` instead of `{'host': {}}`. What do you think about changing `get_values()` to something like this:
```python
    def get_values(self):
        """Correctly set the ``owner_type`` attribute."""
        attrs = super(Host, self).get_values()
        if hasattr(attrs, '_owner_type'):
            attrs['owner_type'] = attrs.pop('_owner_type')
        else:
            attrs.pop('_owner_type')
        return attrs
```

Updated the PR.

**Comment by Ichimonji10** [comment]
> What do you think about changing `get_values()` to something like this:

I think I messed up there. `hasattr` isn't the right tool to inspect the contents of a dict. :cry: I think something like this is more what is intended:

```python
def get_values():
    attrs = super(Host, self).get_values()
    if '_owner_type' in attrs:
        attrs['owner_type'] = attrs.pop('_owner_type')
    return attrs
```

**Comment by abalakh** [comment]
@Ichimonji10 proposed option is better, of course, but the issue is different:
because of [this](https://github.com/SatelliteQE/nailgun/pull/260/files#diff-3822710a997c3f2f7c3e93e884af69caR2036) line we'll always have `self._owner_type == None`, so
```python
    if '_owner_type' in attrs:
        attrs['owner_type'] = attrs.pop('_owner_type')
```
will always create attribute `owner_type` (at least equal to `None`), even if it wasn't defined in initialized entity instance.
As a result, default `Host().update_payload()` will look like this `{'host': {'owner_type': None}}` instead of `{'host': {}}`. Of course, i can fix unit tests and pretend it's supposed to work like that, but that's just wrong way of solving the issue :smile: 
So imo something like this should be applied:
```python
    def get_values(self):
        """Correctly set the ``owner_type`` attribute."""
        attrs = super(Host, self).get_values()
        if '_owner_type' in attrs and attrs['_owner_type'] is not None:
            attrs['owner_type'] = attrs.pop('_owner_type')
        else:
            attrs.pop('_owner_type')
        return attrs
```

**Comment by Ichimonji10** [comment]
> So imo something like this should be applied:

:+1:

**Comment by Ichimonji10** [comment]
This solution looks great to me. Have you tested this out? I'm going to assume so - you've done a great job with thinking this through so far.

ACK

**Comment by abalakh** [comment]
Added unit tests & made a rebase.
@Ichimonji10 i had been testing it while implementing and debugging, unfortunately forgot to save command line output to paste here later :disappointed: 
Anyway, 4 new unit tests + tests from robottelo (SatelliteQE/robottelo#3298) should prove it's working:
```python
py.test tests/foreman/api/test_host.py -k 'test_positive_create_with_usergroup or test_positive_update_usergroup'
================================ test session starts =================================
platform linux2 -- Python 2.7.10, pytest-2.8.7, py-1.4.31, pluggy-0.3.1
rootdir: /home/andrii/workspace/robottelo, inifile: 
plugins: xdist-1.13.1, repeat-0.2
collected 45 items 

tests/foreman/api/test_host.py ..

 43 tests deselected by '-ktest_positive_create_with_usergroup or test_positive_update_usergroup' 
====================== 2 passed, 43 deselected in 49.19 seconds ======================
```

**Comment by abalakh** [comment]
PR is ready for a final review :)

**Comment by sthirugn** [comment]
ACK

**Pull request merged**
