### PR TITLE
Add ActivationKey service_level field

### PR DESCRIPTION
**Pull request by ldjebran**
```console
In[9]: ak = entities.ActivationKey(server_config, service_level='Premium').create(create_missing=True)
In[10]: ak.read()
Out[10]: nailgun.entities.ActivationKey(host_collection=[], service_level=None, max_hosts=None, content_view=None, description=None, unlimited_hosts=True, environment=None, auto_attach=True, organization=nailgun.entities.Organization(id=105), id=65, name=u'ZYbPnwr')
In[11]: ak.service_level
Out[11]: u'Premium'
In[12]: ak2 = entities.ActivationKey(server_config).create(create_missing=True)
In[13]: ak2.service_level

In[14]: ak2.read()
Out[14]: nailgun.entities.ActivationKey(host_collection=[], service_level=None, max_hosts=None, content_view=None, description=None, unlimited_hosts=True, environment=None, auto_attach=True, organization=nailgun.entities.Organization(id=106), id=66, name=u'gIvdXEZLYwKx')
In[15]: ak
Out[15]: nailgun.entities.ActivationKey(host_collection=[], service_level=u'Premium', max_hosts=None, content_view=None, description=None, unlimited_hosts=True, environment=None, auto_attach=True, organization=nailgun.entities.Organization(id=105), id=65, name=u'ZYbPnwr')
```
add this command 
```console
In[39]: ak = ak.read()
In[40]: ak.service_level
In[41]: print ak.service_level
None
```
The service level was silently changed by the server as it make no sense without subscription, and the validation is done when updating the activation with service level, as subscriptions can be added on an already created activation key 
```console
In[42]: ak.service_level = 'Premium'
In[43]: ak.update(['service_level'])
WARNING:nailgun.client:Received HTTP 500 response: {"displayMessage":"Task d4096510-9b11-4088-bbea-9a90beabb9d2: Katello::Errors::CandlepinError: Service level 'Premium' is not available to units of organization pzUUVNtpw.","errors":["Task d4096510-9b11-4088-bbea-9a90beabb9d2: Katello::Errors::CandlepinError: Service level 'Premium' is not available to units of organization pzUUVNtpw."]}
Traceback (most recent call last):
```
when adding the subscription to activation key 
updating:
```
In[19]: ak.service_level = 'Premium'
In[20]: ak.update(['service_level'])
Out[20]: nailgun.entities.ActivationKey(host_collection=[], service_level=u'Premium', max_hosts=None, content_view=None, description=None, unlimited_hosts=True, environment=None, auto_attach=True, organization=nailgun.entities.Organization(id=130), id=91, name=u'NXUVDR')
In[21]: ak.service_level
Out[21]: 'Premium'
In[22]: ak
Out[22]: nailgun.entities.ActivationKey(host_collection=[], service_level='Premium', max_hosts=None, content_view=None, description=None, unlimited_hosts=True, environment=None, auto_attach=True, organization=nailgun.entities.Organization(id=130), id=91, name=u'NXUVDR')
```
reading:
```
In[29]: ak = ak.read()
2017-09-14 15:01:49 - nailgun.client - DEBUG - Making HTTP GET request to https://dell-per415-02.dsal.lab.eng.bos.redhat.com/katello/api/v2/activation_keys/91 with options {'verify': False, 'auth': ('admin', 'changeme'), 'headers': {'content-type': 'application/json'}}, no params and no data.
2017-09-14 15:01:51 - nailgun.client - DEBUG - Received HTTP 200 response:   {"id":91,"name":"NXUVDR","description":null,"unlimited_hosts":true,"auto_attach":true,"content_view_id":null,"environment_id":null,"usage_count":0,"user_id":3,"max_hosts":null,"release_version":null,"service_level":"Premium","content_overrides":[],"organization":{"name":"tXPwCvBPWEVj","label":"tXPwCvBPWEVj","id":130},"created_at":"2017-09-14 10:54:33 UTC","updated_at":"2017-09-14 10:54:34 UTC","content_view":null,"environment":null,"products":[{"id":1989,"name":"Red Hat Enterprise Linux Resilient Storage for RHEL Server - Extended Update Support"},{"id":1990,"name":"Red Hat Software Collections for RHEL Server"},{"id":1992,"name":"Red Hat Enterprise Linux Atomic Host Beta"},{"id":1993,"name":"Red Hat Developer Tools Beta for RHEL Server"},{"id":1994,"name":"Red Hat Enterprise Linux High Availability for RHEL Server - Extended Update Support"},{"id":1995,"name":"Red Hat Developer Tools for RHEL Server"},{"id":1996,"name":"Red Hat EUCJP Support for RHEL Server - Extended Update Support"},{"id":1997,"name":"Red Hat Beta"},{"id":1998,"name":"Red Hat Enterprise Linux Server - Extended Update Support"},{"id":1999,"name":"Oracle Java for RHEL Server - Extended Update Support"},{"id":2000,"name":"Red Hat Enterprise Linux High Performance Networking for RHEL Server - Extended Update Support"},{"id":2001,"name":"Red Hat Enterprise Linux Scalable File System for RHEL Server - Extended Update Support"},{"id":2002,"name":"Oracle Java for RHEL Server"},{"id":2003,"name":"Red Hat Enterprise Linux Load Balancer for RHEL Server - Extended Update Support"},{"id":2004,"name":"Red Hat Enterprise Linux Server"},{"id":2005,"name":"dotNET on RHEL for RHEL Server"},{"id":2006,"name":"Red Hat Software Collections Beta for RHEL Server"},{"id":2007,"name":"Red Hat Enterprise Linux Atomic Host"},{"id":2008,"name":"Red Hat S-JIS Support for RHEL Server - Extended Update Support"},{"id":2009,"name":"Red Hat Developer Toolset for RHEL Server"},{"id":2025,"name":"dotNET on RHEL Beta for RHEL Server"},{"id":2026,"name":"Red Hat Container Images Beta"},{"id":2027,"name":"Red Hat Container Images"}],"host_collections":[],"permissions":{"view_activation_keys":true,"edit_activation_keys":true,"destroy_activation_keys":true}}

In[30]: ak
Out[30]: nailgun.entities.ActivationKey(host_collection=[], service_level=u'Premium', max_hosts=None, content_view=None, description=None, unlimited_hosts=True, environment=None, auto_attach=True, organization=nailgun.entities.Organization(id=130), id=91, name=u'NXUVDR')
In[31]: ak.service_level
Out[31]: u'Premium'
```

Please contact for the full log

### CODE REVIEW

**Comment by ldjebran** [comment]
@oshtaier there is no problem of reading, the server silently change that value to None in creation stage
if yo want to update that activation key with that have no subscription, the server will return an error,
if the activation key has a subscription the value can be updated after passing the server validation and properly read.

**Comment by ldjebran** [comment]
you you want me to mock server validation behavior?

**Comment by ldjebran** [comment]
@oshtaier please note that at creation stage the activation has no subscription.

**Comment by oshtaier** [comment]
I am just curious whether we can check that we have None for AK without subscription and have something for AK with it on unit test level even before we get to actual tests. It is nice validation to have and it is suitable for unit tests level as we just verify basic functionality for entity, actually that entity behave in correct way at all. Anyway, it is thing for discussion, if you see that will take more than few lines of code or more than one hour for implementation, please ignore the idea and treat that message as ACK from me

**Comment by ldjebran** [comment]
@oshtaier to make that unitest I should have as a minimum a specification document saying that it will work like and not else, for now I can only notice the functionality behavior.

**Comment by ldjebran** [comment]
@oshtaier think this unit test scenario make no sense on client side and must be part of a server side unit testing

**Pull request merged**
