### PR TITLE
Update list of OS families

### PR DESCRIPTION
**Pull request by oshtaier**
- Update list of possible OS families according to UI:
image

- Remove duplication of code for Media entity as it has same list of operation systems:
image

Verified that change works properly using `test_update_with_new_os` test from `api/test_partitiontable.py`

Corresponding update for robottelo part will be provided soon (there are no impact by any of that change, so we are free to merge current PR whenever we like)

### CODE REVIEW

**Comment by abalakh** [comment]
ACK

**Comment by elyezer** [comment]
@oshtaier do you know if there is an API path to get that information?

ACK

**Comment by oshtaier** [comment]
In case of exception - I get next response:
```
Received HTTP 422 response: {
  "error": {"id":null,"errors":{"os_family":["must be one of [ AIX, Altlinux, Archlinux, Debian, Freebsd, Gentoo, Junos, Redhat, Solaris, Suse, Windows ]"]},"full_messages":["Operating system family must be one of [ AIX, Altlinux, Archlinux, Debian, Freebsd, Gentoo, Junos, Redhat, Solaris, Suse, Windows ]"]}
}
```
so I guess that we have that list somewhere, but I do not see direct request to the server in apidoc that will suffice our needs. Anyway, that fact can be investigated further

**Comment by Ichimonji10** [comment]
:+1:

**Comment by elyezer** [comment]
@oshtaier thanks for the information. We can take a look on it later.

**Pull request merged**
