### PR TITLE
Update the ForemanTask entity

### PR DESCRIPTION
**Pull request by Ichimonji10**
Do the following:

* Add `EntitySearchMixin` as a parent class.
* Add a `summary` method.
* Add several fields.
* Update the `path` method.
* Update unit tests.

Manual test results:

```python
>>> from nailgun import entities
>>> foreman_tasks = entities.ForemanTask().search()
>>> type(foreman_tasks), len(foreman_tasks)
(<class 'list'>, 20)
>>> for i in range(5):
...     foreman_tasks[i].id
...
'4b749daf-1099-4a3b-ba27-1344252b1ea9'
'43dc1a1b-db54-4bdb-980e-0a84d8581651'
'1911f386-3809-4741-a15d-9bf88d5670d6'
'dcbb2a71-a2a5-42ff-ac60-a690bb6dc3a4'
'be4e9578-c07d-4656-8c6c-14a6d71801b3'
>>> foreman_task = foreman_tasks[0].read()
>>> foreman_task.get_values().keys()
dict_keys(['state', 'ended_at', 'id', 'output', 'label', 'pending', 'progress', 'cli_example', 'input', 'result', 'username', 'started_at', 'humanized'])
```

### CODE REVIEW

**Comment by Ichimonji10** [comment]
Dependency of SatelliteQE/robottelo#2755.

**Comment by Ichimonji10** [comment]
I need to update the manual test results. Just a moment.

**Comment by Ichimonji10** [comment]
Updated the commit message.

**Comment by sghai** [comment]
ACK

**Comment by omaciel** [comment]
ACK

**Pull request merged**
