### PR TITLE
Fixed ConfigTemplate create and update with TemplateCombination

### LINKED ISSUE #333: ConfigTemplate creating nor updating TemplateCombination
Failing code:

```python
hostgroup = entities.HostGroup().create()
        env=entities.Environment().create()
        template = entities.ConfigTemplate(snippet=False).create()
        template.template_combinations.append({
            'hostgroup_id': hostgroup.id,
            'environment_id': env.id
        })
        print(repr(hostgroup))
        print(repr(env))
        print(repr(template))
        print(repr(template.update()))
```

Result doesn't have TemplateCombination (check last print result):

```python

ConfigTemplate(template_combinations=[{'environment_id': 22, 'hostgroup_id': 42}], snippet=False, locked=False, template_kind=TemplateKind(, id=6), operatingsystem=[], location=[], template=u'\U000242b7\U00028992\U0002b0d1\u70d8\U00022819\U000248ba\U000289eb\U0002a906', organization=[], audit_comment=None, id=193, name=u'CXRZApwBji')
ConfigTemplate( template_combinations=[], snippet=False, locked=False, template_kind=TemplateKind(, id=6), operatingsystem=[],location=[], template=u'\U000242b7\U00028992\U0002b0d1\u70d8\U00022819\U000248ba\U000289eb\U0002a906', organization=[], audit_comment=None, id=193, name=u'CXRZApwBji')
```

This happens because the attribute used when generating json is named "template_combinations". API doc says it must be "template_combinations_attributes" when updating ConfigTemplate: I got it working with the code bellow:

``` python
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import requests
from json import dumps

auth = ('***', '***')

url = 'https://sat.verver/api/v2/config_templates/185'
print(requests.get(url, auth=auth, verify=False).json())


headers = {'content-type': 'application/json'}
print(requests.put(
    url,
    data=dumps({
        'config_template':
            {
                'template_combinations_attributes': [
                    {'hostgroup_id': 2, 'environment_id': 2}
                ]
            }
    }),
    auth=auth,
    verify=False,
    headers=headers).json())

```

 Result:
```python
/home/renzo/PycharmProjects/venvs/robottelo/bin/python /home/renzo/PycharmProjects/robottelo/teste.py
/home/renzo/PycharmProjects/venvs/robottelo/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:838: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/security.html
  InsecureRequestWarning)
{u'template_combinations': [], u'locked': False, u'name': u'upda', u'organizations': [], u'locations': [], u'created_at': u'2016-11-04 15:47:03 UTC', u'os_default_templates': [], u'updated_at': u'2016-11-04 17:07:50 UTC', u'template_kind_name': u'provision', u'snippet': False, u'template_kind_id': 6, u'operatingsystems': [], u'template': u'cat', u'audit_comment': None, u'id': 185}
/home/renzo/PycharmProjects/venvs/robottelo/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:838: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/security.html
  InsecureRequestWarning)
{u'template_combinations': [{u'environment_id': 2, u'provisioning_template_name': u'upda', u'environment_name': u'vRbFXLxuC2', u'hostgroup_id': 2, u'config_template_name': u'upda', u'hostgroup_name': u'CNUigfL', u'provisioning_template_id': 185, u'id': 13, u'config_template_id': 185}], u'locked': False, u'name': u'upda', u'organizations': [], u'locations': [], u'created_at': u'2016-11-04 15:47:03 UTC', u'os_default_templates': [], u'updated_at': u'2016-11-04 17:07:50 UTC', u'template_kind_name': u'provision', u'snippet': False, u'template_kind_id': 6, u'operatingsystems': [], u'template': u'cat', u'audit_comment': None, u'id': 185}
```

### PR DESCRIPTION
**Pull request by renzon**
close #333

## Create

```python

import sys; print('Python %s on %s' % (sys.version, sys.platform))
sys.path.extend(['/home/renzo/PycharmProjects/nailgun'])

>>> from nailgun import entities
>>> from nailgun.config import ServerConfig
>>> cfg=ServerConfig('https://foo.bar',('bar','baz'), verify=False)
>>> env=entities.Environment(cfg, name='env2').create()
>>> hostgroup=entities.HostGroup(cfg, name='hgroup2').create()
>>> combination=entities.TemplateCombination(cfg, hostgroup=hostgroup,
                                         environment=env)
>>> cfg_template=entities.ConfigTemplate(cfg, name='cfg2',
            snippet=False,
            template='cat',
            template_kind=8,
            template_combinations=[combination])
>>> cfg_template.create()
 ConfigTemplate( ServerConfig(url='https://foo.bar', verify=False, auth=('bar', 'baz')), snippet=False, locked=False, template_kind= TemplateKind( ServerConfig(url='https://foo.bar', verify=False, auth=('bar', 'baz')), id=8), operatingsystem=[], template_combinations=[{u'environment_id': 24, u'provisioning_template_name': u'cfg2', u'environment_name': u'env2', u'hostgroup_id': 44, u'config_template_name': u'cfg2', u'hostgroup_name': u'hgroup2', u'provisioning_template_id': 195, u'id': 16, u'config_template_id': 195}], location=[], template=u'cat', organization=[], audit_comment=None, id=195, name=u'cfg2')
```
##Update
 ```python

import sys; print('Python %s on %s' % (sys.version, sys.platform))
sys.path.extend(['/home/renzo/PycharmProjects/nailgun'])


>>> from nailgun import entities
>>> from nailgun.config import ServerConfig
>>> cfg=ServerConfig('https:foo.bar',('bar', 'baz'), verify=False)
>>> cfg_template=entities.ConfigTemplate(cfg, name='to_update',
            snippet=False,
            template='cat',
            template_kind=8).create()
>>> cfg_template.template_combinations
[]
>>> env=entities.Environment(cfg, name='env').create()
>>> hostgroup=entities.HostGroup(cfg, name='hg').create()
>>> cfg_template.template_combinations.append(
    entities.TemplateCombination(cfg, hostgroup=hostgroup, environment=env)
)
>>> cfg_template = cfg_template.update()
>>> cfg_template.template_combinations
[{u'environment_id': 25, u'provisioning_template_name': u'to_update', u'environment_name': u'env', u'hostgroup_id': 46, u'config_template_name': u'to_update', u'hostgroup_name': u'hg', u'provisioning_template_id': 196, u'id': 17, u'config_template_id': 196}]

```

### CODE REVIEW

**Comment by omaciel** [comment]
@svtkachenko @abalakh mind reviewing this?

**Comment by abalakh** [comment]
Are you sure you need separate parser for this specific case? Till now naigun was clever enough to parse everything correctly.
Issues with different parameter names in GET/POST/PUT requests are not new, we have numerous workarounds for such cases, but basically each time adding something like this was enough:
```python
    def update_payload(self, fields=None):
        payload = super(EntityNameHere, self).update_payload(fields)
        if 'old_field_name' in payload:
            payload['new_field_name'] = payload.pop('old_field_name')
        return payload
```
(and similar for create_payload() and read() if needed)

**Comment by renzon** [comment]
@abalakh good question. template_combination is a [ListField](https://github.com/SatelliteQE/nailgun/blob/master/nailgun/entities.py#L931) and [_payload](https://github.com/SatelliteQE/nailgun/blob/master/nailgun/entity_mixins.py#L185) doesn't handle this kind when the list contains other entities. Just sent another commit handling it on _payload itself. This way every Entity will parse ListField accordingly.

**Comment by abalakh** [comment]
@renzon 👍 great, thanks.
Now i can't see real value in `_fix_payload()` - by saving only 2 lines of similar code you're increasing code complexity and, basically, resolving common issue in a different manner.
Any concerns against just updating body of `create_payload` and `update_payload` to smth like this:
```python
        payload = super(ConfigTemplate, self).create_payload()
        if 'template_combinations' in payload:
            payload['template_combinations_attributes'] = payload.pop(
                'template_combinations')
        return {'config_template': payload}
```
?

**Pull request merged**
