### PR TITLE
Fixing Activations Key entity according to 6.2

### PR DESCRIPTION
**Pull request by oshtaier**
```
>>> test = entities.ActivationKey().create(create_missing=True)
>>> test
nailgun.entities.ActivationKey(nailgun.config.ServerConfig(url=u'https://server', verify=False, auth=(u'admin', u'changeme')), host_collection=[], max_hosts=None, content_view=None, description=None, unlimited_hosts=True, environment=None, auto_attach=True, organization=nailgun.entities.Organization(nailgun.config.ServerConfig(url=u'https://server', verify=False, auth=(u'admin', u'changeme')), id=1240), id=102, name=u'org_name')
```

### CODE REVIEW

**Comment by abalakh** [comment]
ACK

**Comment by elyezer** [comment]
ACK. Since I saw the conversation about creating a branch for GA and Beta on https://github.com/SatelliteQE/robottelo/pull/3434, I will not merge this until we have sure about that.

**Comment by abalakh** [comment]
@elyezer we won't introduce branching for nailgun, @sthirugn planned to branch robottelo only. Although i'm not sure why do we need branches at all then, as it won't be possible to use beta-robottelo with latest nailgun

**Comment by oshtaier** [comment]
@elyezer @abalakh 
I always hate to have all these `if _get_version(server_config) < Version('6.2'):` things and prefer branching as nailgun.entities already has ~4500 lines of code and all these conditions do not make our lives easier
+Even more issues with unit tests to support all these things

Maybe we can move to branching? :)

**Comment by elyezer** [comment]
Instead of branching we can say for Sat 6.0 use nailgun X.Y, for Sat 6.1 use nailgun Z.A... There is no need to branch I think since the previous will not likely receive any update. Yes I'm being lazy and trying to have the management simple.

I would like to hear from @Ichimonji10 what he thinks about it.

**Comment by Ichimonji10** [comment]
Nailgun isn't set up to deal with different versions of Satellite in a nice way. The conditionals just get out of hand way too fast. I like @elyezer's solution. It's simple. Let's stick with trying to be compatible with the current version of Satellite, pending some huge need otherwise.

**Comment by elyezer** [comment]
A new release of NailGun was released a new branch was created. We are safe to deliver updates for the GA builds.

**Comment by elyezer** [comment]
@oshtaier can you please rebase so we can merge this?

**Comment by oshtaier** [comment]
Closing, because #284 is already addressing the issue

**Pull request closed without merging**
