### PR TITLE
add host_ids field to host collection

### PR DESCRIPTION
**Pull request by swadeley**
Hello

This update is to enable adding hosts to a host collection. 

This has not been working before, but the problem only came to light after https://github.com/SatelliteQE/nailgun/pull/757

### CODE REVIEW

**Review by mirekdlugosz — COMMENTED** [review]
I'm not convinced this is the way forward. `_payload` in `nailgun/entity_mixins.py` is responsible for translating `OneToManyField` field to `{name}_ids` that is list of ids from entities: https://github.com/SatelliteQE/nailgun/blob/master/nailgun/entity_mixins.py#L182

I think change like that should be applied on framework level, not on each entity level. There are probably many more entities currently broken.

@lhellebr @mshriver @JacobCallahan

**Comment by swadeley** [comment]
> I think change like that should be applied on framework level,

@mirekdlugosz Unfortunately I do not understand what to do

**Comment by JacobCallahan** [comment]
@swadeley he is recommending you add something more general to the most applicable mixin.

**Comment by swadeley** [comment]
the test is now passing without this change https://github.com/SatelliteQE/robottelo/pull/8197#issuecomment-765912236

**Pull request closed without merging**
