### PR TITLE
Adding DockerContentViewFilter

### PR DESCRIPTION
**Pull request by valleedelisle**
We need an entity for the docker type content view filter

Signed-off-by: David Vallee Delisle <dvd@redhat.com>

### CODE REVIEW

**Review by mshriver — APPROVED** [review]
I'm really just a tier1 reviewer in this context, code wise it looks good to me. I wouldn't know if it were incomplete for the entity though.

**Comment by valleedelisle** [comment]
Honestly I just added Docker everywhere I saw Erratum and it works for me. I looked up and there's not much difference between both filters.

**Review by JacobCallahan — APPROVED** [review]
ACK.
@mshriver do you want to merge this and rebase/reapply your changes or have this PR follow yours?

**Comment by mshriver** [comment]
@JacobCallahan I say merge this and #766 and I'll eat the rebase.

**Comment by valleedelisle** [comment]
Thanks for the merge.

**Pull request merged**
