### PR TITLE
[cherry-pick] Add support for reading subscriptions

### PR DESCRIPTION
**Pull request by mirekdlugosz**
Cherry-pick #754 into `stable-satellite` branch.

### CODE REVIEW

**Review by lhellebr — APPROVED** [review]
LGTM

**Review by jameerpathan111 — APPROVED** [review]
ACK

**Comment by jameerpathan111** [comment]
Need one more tier reviewer's ack here.

**Comment by jameerpathan111** [comment]
@SatelliteQE/nailgun-tier-2-reviewers

**Review by jyejare — APPROVED** [review]

**Pull request merged**
