### PR TITLE
Removes Singnals.py as we no longer use it

### LINKED ISSUE #621: Remove `blinker_herald` dependency
I wanted to start a discussion around removing the `blinker_herald`.. 

I would like to remove `blinker_herald` as a dependency for Nailgun, as part of my work for with foreman-ansible-modules we would like to start packaging Nailgun as an RPM.

It would be easier to package without `blinker_herald` as if Nailgun, as it currently does, depends on it, I would have to package that first. So I ask, are we open to removing this dependency? If so, what would be the least painful approach to take?

Looking forward to a productive discussion. Thanks!

### PR DESCRIPTION
**Pull request by san7ket**
Fixes #621

### CODE REVIEW

**Comment by ntkathole** [comment]
[test]

**Comment by mirzal** [comment]
I think you also need to remove `docs/signals.rst` file, and references to signals in `requirements-dev.txt` and `docs/index.rst` files.

**Comment by mirzal** [comment]
@san7ket do you think we should merge it before creating 6.5.z branch?

My opinion is that we should merge it after branching, but I would like confirmation.

**Comment by san7ket** [comment]
Yes, After branching, this is blocked due to testing. We need to test the change and then we can merge

**Comment by JacobCallahan** [comment]
@san7ket if you get a chance to test this, now is the perfect time to merge.

**Comment by san7ket** [comment]
= 20 failed, 394 passed, 1 skipped, 610 deselected, 42 warnings, 60 error in 1914.17 seconds =

Tier1 Api tests, were run. I looked into failures but those were not related. Standalone Job `/view/Satellite 6/job/satellite6-standalone-automation/1528/console`

**Comment by mirzal** [comment]
For the record, my comment from [April 26th](https://github.com/SatelliteQE/nailgun/pull/630#issuecomment-487013662) still stands:

> I think you also need to remove `docs/signals.rst` file, and references to signals in `requirements-dev.txt` and `docs/index.rst` files.

**Comment by san7ket** [comment]
Thanks for the reminder , will get on it

**Comment by san7ket** [comment]
@mirzal Addressed the comment

**Comment by san7ket** [comment]
Test would fail until https://github.com/SatelliteQE/robottelo/pull/6880

**Comment by san7ket** [comment]
ok to test: tests/foreman/api/test_activationkey.py -m tier1

**Comment by san7ket** [comment]
ok to test: tests/foreman/api/test_activationkey.py -m tier1

**Comment by san7ket** [comment]
ok to test: tests/foreman/api/test_activationkey.py -m tier1

**Comment by san7ket** [comment]
ok to test: tests/foreman/api/test_activationkey.py -m tier1

**Comment by san7ket** [comment]
ok to test : tests/foreman/api/test_activationkey.py -m tier1

**Comment by san7ket** [comment]
ok to test : tests/foreman/api/test_activationkey.py -m tier1

**Comment by san7ket** [comment]
Tests passing now , 1 Failure unrelated to the change here

**Pull request merged**
