### PR TITLE
Remove codecov

### PR DESCRIPTION
**Pull request by JacobCallahan**
This continues a trend we've done with other projects. Codecov has some use in other types of projects, but really isn't a good fit for Nailgun since it is functionally exercised by Robottelo.

Without getting too deep into philosophy, CodeCov is a misleading metric for quality and minor changes are largely ignored in mature projects.

### CODE REVIEW

**Review by omkarkhatavkar — APPROVED** [review]

**Comment by jyejare** [comment]
Here are some personal thoughts:

TBH we caught many issues in the past in nailgun using unit tests before merge the PR.

I agree that its an extra overhead but nailgun has simplified form of unit tests where sometimes adding just a line covers the new function.

Also In SatelliteQE testing, we are very dependent on API testing and unit tests here serves as a sanity for automation failures in API functions added in nailgun.

**Comment by JacobCallahan** [comment]
I'm not saying get rid of the unit tests, I'm saying get rid of codecov as it's a poor measurement of useful tests.

**Comment by jyejare** [comment]
Sure @JacobCallahan , but then could we run tests as part of Pull Request WF to ensure none is failing ?

**Comment by JacobCallahan** [comment]
@jyejare oohh I didn't even notice that we weren't running tests. Added that to the pull request workflow and they're passing.

**Review by jyejare — APPROVED** [review]

**Review by ogajduse — APPROVED** [review]

**Pull request merged**
