### PR TITLE
Add filter_host_parents and exclude_host_parents options for virt-who entity

### PR DESCRIPTION
**Pull request by hkx303**
1. Add filter_host_parents and exclude_host_parents options
2. Sort the fields by alphabetically.

### CODE REVIEW

**Comment by ntkathole** [comment]
ok to test : tests/foreman/api/test_virt_who_config.py

**Comment by ntkathole** [comment]
This PR will break the robottelo tests from tests/foreman/api/test_virt_who_config.py and tests/foreman/ui/test_dashboard.py -k test_positive_virtwho_configs_widget

```
                'Valid fields are {0}, but received {1} instead.'
>               .format(self._fields.keys(), kwargs.keys())
            )
E           nailgun.entity_mixins.NoSuchFieldError: Valid fields are dict_keys(['blacklist', 'debug', 'exclude_host_parents', 'filter_host_parents', 'filtering_mode', 'hypervisor_id', 'hypervisor_password', 'hypervisor_server', 'hypervisor_type', 'hypervisor_username', 'interval', 'name', 'no_proxy', 'organization_id', 'proxy', 'satellite_url', 'status', 'whitelist', 'id']), but received dict_keys(['name', 'organization', 'hypervisor_server', 'satellite_url', 'hypervisor_type', 'hypervisor_username', 'hypervisor_id', 'hypervisor_password']) instead.
```

**Comment by hkx303** [comment]
> This PR will break the robottelo tests from tests/foreman/api/test_virt_who_config.py and tests/foreman/ui/test_dashboard.py -k test_positive_virtwho_configs_widget
> 
> ```
>                 'Valid fields are {0}, but received {1} instead.'
> >               .format(self._fields.keys(), kwargs.keys())
>             )
> E           nailgun.entity_mixins.NoSuchFieldError: Valid fields are dict_keys(['blacklist', 'debug', 'exclude_host_parents', 'filter_host_parents', 'filtering_mode', 'hypervisor_id', 'hypervisor_password', 'hypervisor_server', 'hypervisor_type', 'hypervisor_username', 'interval', 'name', 'no_proxy', 'organization_id', 'proxy', 'satellite_url', 'status', 'whitelist', 'id']), but received dict_keys(['name', 'organization', 'hypervisor_server', 'satellite_url', 'hypervisor_type', 'hypervisor_username', 'hypervisor_id', 'hypervisor_password']) instead.
> ```

Hi @ntkathole ,
We added our new virt-who testcases in 
```
robottelo/tests/foreman/virtwho/test_ui_virtwho.py
robottelo/tests/foreman/virtwho/test_api_virtwho.py
robottelo/tests/foreman/virtwho/test_cli_virtwho.py
```
and next step, we will look into virt-who tests docstrings designed by Perry and will make sure to remove duplicates and move the valid ones under new virtwho framework.

**Comment by ntkathole** [comment]
@hkx303 you need to cherry-pick this commit to stable-satellite branch as robottelo uses that branch

**Comment by hkx303** [comment]
> @hkx303 you need to cherry-pick this commit to stable-satellite branch as robottelo uses that branch

Ohh, thanks for the reminder.  : )

**Pull request merged**
