### PR TITLE
Document and test bug workarounds

### PR DESCRIPTION
**Pull request by Ichimonji10**
NailGun has several bug workaround that are not documented. File bugs for many of those workaround and link to the relevant bugs. Add unit tests for the workarounds. Of note:

* In the process of documenting existing workarounds, I've discovered more bugs and written a few new workarounds.
* I've changed the fields on the HostGroup and Host entities.

### CODE REVIEW

**Comment by Ichimonji10** [comment]
This is being done as part of #115. There are still four more methods left to investigate and document.

**Comment by JacobCallahan** [comment]
ACK

**Comment by Ichimonji10** [comment]
Rebased

**Comment by abalakh** [comment]
ACK

**Comment by oshtaier** [comment]
Nice one PR. It will be necessary to re-test robottelo functionality once these fixes will be released :)

**Comment by elyezer** [comment]
:+1:

**Pull request merged**
