### PR TITLE
adding properties to activation key

### PR DESCRIPTION
**Pull request by tstrych**
##### Description of changes
adding missing properties to activation key based on sat 6.9 apidoc

### CODE REVIEW

**Comment by jameerpathan111** [comment]
@tstrych can you provide test result for this change?

**Comment by tstrych** [comment]
sorry, i forget
definitely :+1:

**Review by mshriver — APPROVED** [review]

**Review by jameerpathan111 — APPROVED** [review]
LGTM

**Review by lhellebr — APPROVED** [review]

**Comment by tstrych** [comment]
I have 3 ack's. Mike is maintainer, and Lukas is tier1 reviewer.  Also thanks Jameer for your comments. Merging...

**Pull request merged**
