### PR TITLE
Incorporate blinker_herald as part of nailgun

### PR DESCRIPTION
**Pull request by san7ket**

### CODE REVIEW

**Comment by rochacbruno** [comment]
Why?

Is signals in use somewhere?

**Comment by san7ket** [comment]
@rochacbruno Ahh I am so sorry, I should have provided you with some context. The issue is https://github.com/SatelliteQE/nailgun/issues/621

**Comment by rochacbruno** [comment]
Commented here: https://github.com/SatelliteQE/nailgun/issues/621#issuecomment-479486163

**Comment by JacobCallahan** [comment]
Based on bruno's comment linked above, we can close this. Thanks for the PR though, @san7ket!

**Comment by san7ket** [comment]
Closing this

**Pull request closed without merging**
