### PR TITLE
utf8 value for login is removed as it is rejected by satellite

### PR DESCRIPTION
**Pull request by sthirugn**

### CODE REVIEW

**Comment by Ichimonji10** [comment]
This PR changes the `login` field, but #2805 makes reference to the `lastname` field. What explains the difference?

**Comment by sthirugn** [comment]
@Ichimonji10 see https://github.com/SatelliteQE/robottelo/issues/2805#issuecomment-143798781

**Comment by JacobCallahan** [comment]
ACK

**Comment by Ichimonji10** [comment]
ACK

**Pull request merged**
