### PR TITLE
Added Setting entity

### PR DESCRIPTION
**Pull request by abalakh**
Added Setting entity and some tests accordingly.

Examples of usage:
1) Read
```python
>>> entities.Setting(id=34).read()
nailgun.entities.Setting(nailgun.config.ServerConfig(url=u'https://***********************************.com', verify=False, auth=(u'admin', u'********')), default=20, created_at=u'2015-09-07T08:07:46Z', description=u'Number of records shown per page in Foreman', updated_at=u'2015-09-07T11:37:35Z', value=42, settings_type=u'integer', id=34, name=u'entries_per_page')
```
2) Search
```python
>>> entities.Setting().search(query={'search': 'name="entries_per_page"'})
[nailgun.entities.Setting(nailgun.config.ServerConfig(url=u'https://***********************************.com', verify=False, auth=(u'admin', u'********')), default=20, created_at=u'2015-09-07T08:07:46Z', description=u'Number of records shown per page in Foreman', updated_at=u'2015-09-07T11:37:35Z', value=42, settings_type=u'integer', id=34, name=u'entries_per_page')]
```
3) Update
```python
>>> per_page = entities.Setting().search(query={'search': 'name="entries_per_page"'})[0]
>>> per_page.value = '30'
>>> per_page.update({'value'})
nailgun.entities.Setting(nailgun.config.ServerConfig(url=u'https://***********************************.com', verify=False, auth=(u'admin', u'********')), default=20, created_at=u'2015-09-07T08:07:46Z', description=u'Number of records shown per page in Foreman', updated_at=u'2015-09-07T12:38:44Z', value=30, settings_type=u'integer', id=34, name=u'entries_per_page')
```

### CODE REVIEW

**Comment by oshtaier** [comment]
Could we operate with any setting or 'entries_per_page' only at that moment?

**Comment by oshtaier** [comment]
Just curious whether we will need to add more fields in future or it is full set

**Comment by oshtaier** [comment]
ACK pending question

**Comment by abalakh** [comment]
@oshtaier I haven't tried literally every setting, but, theoretically, they all should be fine.
`entities.Setting().search()` returns list of all settings, reading/searching/updating random setting is ok:
```python
>>> entities.Setting(id=42).read()
nailgun.entities.Setting(nailgun.config.ServerConfig(url=u'https://***********************************.com', verify=False, auth=(u'admin', u'********')), default=60, created_at=u'2015-09-07T08:07:46Z', description=u'Max timeout for REST client requests to smart-proxy', updated_at=u'2015-09-07T08:07:46Z', value=60, settings_type=u'integer', id=42, name=u'proxy_request_timeout')

>>> entities.Setting(id=13).read()
nailgun.entities.Setting(nailgun.config.ServerConfig(url=u'https://***********************************.com', verify=False, auth=(u'admin', u'********')), default=u'Satellite Kickstart Default Finish', created_at=u'2015-09-07T08:07:46Z', description=u'Default finish template for new Operating Systems', updated_at=u'2015-09-07T08:07:46Z', value=u'Satellite Kickstart Default Finish', settings_type=u'string', id=13, name=u'satellite_default_finish')

>>> blah = entities.Setting(id=42).read()
>>> blah.value = '61'
>>> blah.update({'value'})
nailgun.entities.Setting(nailgun.config.ServerConfig(url=u'https://***********************************.com', verify=False, auth=(u'admin', u'********')), default=60, created_at=u'2015-09-07T08:07:46Z', description=u'Max timeout for REST client requests to smart-proxy', updated_at=u'2015-09-07T14:41:32Z', value=61, settings_type=u'integer', id=42, name=u'proxy_request_timeout')

```

**Comment by sthirugn** [comment]
ACK

**Comment by Ichimonji10** [comment]
This looks great. ACK.

**Pull request merged**
