### PR TITLE
Added/extented entities of SRPMs and content_type

### PR DESCRIPTION
**Pull request by vijay8451**
- Added support for `Content_type`.
- Added `Srpms` entities with respective test.

### CODE REVIEW

**Comment by ntkathole** [comment]
ok to test : tests/foreman/api/test_puppetmodule.py tests/foreman/ui/test_repository.py tests/foreman/api/test_repository_set.py tests/foreman/api/test_errata.py

**Comment by ntkathole** [comment]
ok to test : "tests/foreman/api/test_puppetmodule.py tests/foreman/api/test_repository_set.py tests/foreman/api/test_errata.py"

**Comment by ntkathole** [comment]
ok to test : tests/foreman/api/test_puppetmodule.py tests/foreman/api/test_repository_set.py tests/foreman/api/test_errata.py

**Comment by vijay8451** [comment]
@ntkathole ` Build 94 has 4 tests run, 0 skipped, 0 failed` :+1:

**Comment by jyejare** [comment]
ok to test : tests/foreman/api/test_puppetmodule.py tests/foreman/api/test_repository_set.py tests/foreman/api/test_errata.py

**Comment by vijay8451** [comment]
@jyejare @ntkathole If not any blocker here , please merge as branching is done.

**Pull request merged**
