### PR TITLE
Add host to HostCollection updatable_fields

### PR DESCRIPTION
**Pull request by swadeley**
Hello

Adding 'host' to  updatable_fields list for Host Collection

### CODE REVIEW

**Comment by swadeley** [comment]
Before change, this error was seen:

>       host_collection = host_collection.update(['host'])

tests/foreman/api/test_hostcollection.py:226: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../../../.virtualenvs/robottelo_2/lib/python3.8/site-packages/nailgun/entity_mixins.py:1023: in update
    return self.read(attrs=self.update_json(fields))
../../../.virtualenvs/robottelo_2/lib/python3.8/site-packages/nailgun/entity_mixins.py:999: in update_json
    response = self.update_raw(fields)
../../../.virtualenvs/robottelo_2/lib/python3.8/site-packages/nailgun/entity_mixins.py:981: in update_raw
    self.update_payload(fields),
../../../.virtualenvs/robottelo_2/lib/python3.8/site-packages/nailgun/entity_mixins.py:965: in update_payload
    values = {field: values[field] for field in fields}
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

.0 = <list_iterator object at 0x7f00c257a790>

>   values = {field: values[field] for field in fields}
E   KeyError: 'host'

../../../.virtualenvs/robottelo_2/lib/python3.8/site-packages/nailgun/entity_mixins.py:965: KeyError

**Comment by swadeley** [comment]
After change:

robottelo]$ pytest --show-capture=no tests/foreman/api/test_hostcollection.py -k test_positive_add_host
==================================== test session starts ===================================
platform linux -- Python 3.8.6, pytest-5.4.3, py-1.9.0, pluggy-0.13.1
shared_function enabled - OFF - scope:  - storage: file
rootdir: /sat6/robottelo_2/robottelo, inifile: pytest.ini
plugins: ibutsu-1.12, mock-3.3.1, forked-1.3.0, services-2.2.1, cov-2.10.1, xdist-1.34.0
collecting ... 2020-11-25 16:17:34 - conftest - DEBUG - Collected 20 test cases
collected 20 items / 18 deselected / 2 selected                                                                  

tests/foreman/api/test_hostcollection.py ..                                                                [100%]


========================== 2 passed, 18 deselected, 2 warnings in 27.33s ===============

**Comment by lhellebr** [comment]
Looking at `/apidoc/v2/host_collections/update.html`, that field can't be updated. Won't this change just mask a bug in robottelo/nailgun?

**Comment by swadeley** [comment]
> Looking at `/apidoc/v2/host_collections/update.html`, that field can't be updated. Won't this change just mask a bug in robottelo/nailgun?

Oh, I suppose you are right:

https://theforeman.org/plugins/katello/3.15/api/apidoc/v2/host_collections/update.html

 I will take another look at the problem and close this PR.

Thank you

**Comment by swadeley** [comment]
see https://github.com/SatelliteQE/nailgun/pull/777

**Pull request closed without merging**
