### PR TITLE
Add mixins to Image entity

### PR DESCRIPTION
**Pull request by svtkachenko**

### CODE REVIEW

**Comment by oshtaier** [comment]
Add unit tests for mixins

**Comment by svtkachenko** [comment]
@oshtaier Looking into existing tests I think that they are used for entities that override methods from mixins.

**Comment by oshtaier** [comment]
I would check these two places:
https://github.com/SatelliteQE/nailgun/blob/master/tests/test_entities.py#L482
https://github.com/SatelliteQE/nailgun/blob/master/tests/test_entities.py#L1142

**Comment by svtkachenko** [comment]
Yeap, checked that before writing previous comment.
`CreateTestCase`: the list of added entities is much smaller than entire list of entities, all added entities except `ConfigGroup` have overridden `create` or `create_payload` method.
`UpdateTestCase`: the list of added entities is much smaller than entire list of entities, all added entities have overridden `update` or `update_payload` method.

It is not so difficult to add another entity to the tests thanks to its good design, however bloated code is prone to errors so better keep it compacted.
Also @coveralls says that `Coverage remained the same`.

**Pull request merged**
