### PR TITLE
Remove `config_template` in Organization and Location entities

### LINKED ISSUE #714: UI testing for Sat6.8 failed due to organization fields changed
UI testing failed due to the error below:

```
@fixture(scope='module')
    def module_org():
        """Shares the same organization for all tests in specific test module.
        Returns 'Default Organization' by default, override this fixture on
    
        :rtype: :class:`nailgun.entities.Organization`
        """
        default_org_id = (
            nailgun.entities.Organization()
            .search(query={'search': 'name="{}"'.format(DEFAULT_ORG)})[0]
            .id
        )
>       return nailgun.entities.Organization(id=default_org_id).read()

robottelo/tests/foreman/virtwho/conftest.py:28: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/usr/local/lib/python3.7/site-packages/nailgun/entities.py:5250: in read
    return super(Organization, self).read(entity, attrs, ignore, params)
/usr/local/lib/python3.7/site-packages/nailgun/entity_mixins.py:800: in read
    in _get_entity_ids(field_name, attrs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

field_name = 'config_template'
attrs = {'ancestry': None, 'compute_resources': [], 'created_at': '2020-04-30 10:59:51 UTC', 'default_content_view_id': 1, ...}

    def _get_entity_ids(field_name, attrs):
        """Find the IDs for a one to many relationship.
    
        The server may return JSON data in the following forms for a
        :class:`nailgun.entity_fields.OneToManyField`::
    
            'user': [{'id': 1, …}, {'id': 42, …}]
            'users': [{'id': 1, …}, {'id': 42, …}]
            'user_ids': [1, 42]
    
        Search ``attrs`` for a one to many ``field_name`` and return its ID.
    
        :param field_name: A string. The name of a field.
        :param attrs: A dict. A JSON payload as returned from a server.
        :returns: An iterable of entity IDs.
    
        """
        field_name_ids = field_name + '_ids'
        plural_field_name = pluralize(field_name)
        if field_name_ids in attrs:
            return attrs[field_name_ids]
        elif field_name in attrs:
            return [entity['id'] for entity in attrs[field_name]]
        elif plural_field_name in attrs:
            return [entity['id'] for entity in attrs[plural_field_name]]
        else:
            raise MissingValueError(
>               f'Cannot find a value for the "{field_name}" field. '
                f'Searched for keys named {field_name_ids}, {field_name}, {plural_field_name} '
                f'but available keys are {attrs.keys()}.'
            )
E           nailgun.entity_mixins.MissingValueError: Cannot find a value for the "config_template" field. Searched for keys named config_template_ids, config_template, config_templates but available keys are dict_keys(['label', 'redhat_repository_url', 'system_purposes', 'service_levels', 'service_level', 'select_all_types', 'description', 'created_at', 'updated_at', 'ancestry', 'parent_id', 'parent_name', 'id', 'name', 'title', 'users', 'smart_proxies', 'subnets', 'compute_resources', 'media', 'ptables', 'provisioning_templates', 'domains', 'realms', 'environments', 'hostgroups', 'locations', 'hosts_count', 'parameters', 'simple_content_access', 'owner_details', 'default_content_view_id', 'library_id']).

/usr/local/lib/python3.7/site-packages/nailgun/entity_mixins.py:277: MissingValueError
```

Seems the [Organization fields](https://github.com/SatelliteQE/nailgun/blob/master/nailgun/entities.py#L5156) missing the ''config_template'' is the root cause.

### PR DESCRIPTION
**Pull request by hkx303**
Fixes #714 : Setup for UI testing failed

Add the 'config_template' `ignore` in `read()` can fix the issue, works fine for virt-who ui-testing

### CODE REVIEW

**Comment by hkx303** [comment]
Testing result:

```
(venv) [hkx303@kuhuang virtwho]$ pytest test_ui_virtwho.py -k test_positive_deploy_configure_by_id -s
==================================== test session starts =====================================
platform linux -- Python 3.7.3, pytest-4.6.3, py-1.8.0, pluggy-0.12.0
shared_function enabled - OFF - scope:  - storage: file
rootdir: /home/hkx303/Documents/CI/robottelo/robottelo
plugins: services-1.3.1, forked-1.0.2, mock-1.10.4, cov-2.7.1, xdist-1.29.0
collecting ... 2020-05-07 08:07:59 - conftest - DEBUG - Collected 15 test cases
2020-05-07 16:08:01 - robottelo.ssh - DEBUG - Instantiated Paramiko client 0x7f0d96ceb4a8
2020-05-07 16:08:01 - robottelo.ssh - INFO - Connected to [ent-02-vm-08.lab.eng.nay.redhat.com]
2020-05-07 16:08:01 - robottelo.ssh - INFO - >>> rpm -q satellite
2020-05-07 16:08:02 - robottelo.ssh - INFO - <<< stdout
satellite-6.8.0-0.2.beta.el7sat.noarch

2020-05-07 16:08:02 - robottelo.ssh - DEBUG - Destroyed Paramiko client 0x7f0d96ceb4a8
2020-05-07 16:08:02 - robottelo.host_info - DEBUG - Host Satellite version: 6.8
2020-05-07 16:08:02 - robottelo.helpers - DEBUG - Generated file bz_cache.json with BZ collect data
collected 15 items / 14 deselected / 1 selected  

-- Docs: https://docs.pytest.org/en/latest/warnings.html
=================== 1 passed, 14 deselected, 6 warnings in 760.60 seconds ====================
(venv) [hkx303@kuhuang virtwho]$ 

```

**Comment by hkx303** [comment]
> Got the feedback from dev team: config_templates was renamed to provisioinng_templates years ago, and is dropped in 6.8, so provisioinng_templates is supported or not by nailgun?

Hi Eko, we have already supported `provisioning_templates` like https://github.com/SatelliteQE/nailgun/blob/master/nailgun/entities.py#L4835 , so now we just need to drop the `config_template`.

**Comment by hkx303** [comment]
> Since attribute was renamed to `provisioning_templates`, I believe correct course of action is renaming attribute names in:
> 
> * line 4821 (`Location`)
> * line 5156 (`Organization`)
> 
> There are also multiple other references to `config_template`, including `ConfigTemplate` class (entity), but I see a point in merging basic changes required to unblock us as soon as possible, and tackling general problem of renaming in separate PR.

Hi,Mirek, 
actually, we have already created `provisioning_templates`,
see:

- Line 5170(`Organization`)
- Line 4835(`Location`)

**Comment by hkx303** [comment]
> Since attribute was renamed to `provisioning_templates`, I believe correct course of action is renaming attribute names in:
> 
> * line 4821 (`Location`)
> * line 5156 (`Organization`)
> 
> There are also multiple other references to `config_template`, including `ConfigTemplate` class (entity), but I see a point in merging basic changes required to unblock us as soon as possible, and tackling general problem of renaming in separate PR.

Shall we just delete the `config_template` in `Organization` and `Location` ?

**Comment by hkx303** [comment]
New test result:

```
(venv) [hkx303@kuhuang virtwho]$ pytest test_ui_virtwho.py -k test_positive_deploy_configure_by_id -s
==================================== test session starts =====================================
platform linux -- Python 3.7.3, pytest-4.6.3, py-1.8.0, pluggy-0.12.0
shared_function enabled - OFF - scope:  - storage: file
rootdir: /home/hkx303/Documents/CI/robottelo/robottelo
plugins: services-1.3.1, forked-1.0.2, mock-1.10.4, cov-2.7.1, xdist-1.29.0
collecting ... 2020-05-07 13:43:39 - conftest - DEBUG - Collected 15 test cases
2020-05-07 21:43:41 - robottelo.ssh - DEBUG - Instantiated Paramiko client 0x7fe528733438
2020-05-07 21:43:41 - robottelo.ssh - INFO - Connected to [ent-02-vm-08.lab.eng.nay.redhat.com]
2020-05-07 21:43:41 - robottelo.ssh - INFO - >>> rpm -q satellite
2020-05-07 21:43:42 - robottelo.ssh - INFO - <<< stdout
satellite-6.8.0-0.2.beta.el7sat.noarch

2020-05-07 21:43:42 - robottelo.ssh - DEBUG - Destroyed Paramiko client 0x7fe528733438
2020-05-07 21:43:42 - robottelo.host_info - DEBUG - Host Satellite version: 6.8
2020-05-07 21:43:42 - robottelo.helpers - DEBUG - Generated file bz_cache.json with BZ collect data
collected 15 items / 14 deselected / 1 selected   

=================== 1 passed, 14 deselected, 6 warnings in 773.64 seconds ====================
```

**Comment by hkx303** [comment]
@JacobCallahan @jyejare @rochacbruno 
Need Tier 2 ACK, thanks :)

**Comment by mirekdlugosz** [comment]
@hkx303 please remember to cherry-pick this change into `stable-satellite` branch and raise new PR.

**Comment by hkx303** [comment]
> @hkx303 please remember to cherry-pick this change into `stable-satellite` branch and raise new PR.

Gotcha

**Pull request merged**
