### PR TITLE
User data image support added

### PR DESCRIPTION
**Pull request by jyejare**
Create user_data/cloud_init Image support added from Nailgun.

### CODE REVIEW

**Comment by ntkathole** [comment]
ok to test : tests/foreman/api/test_host.py tests/foreman/api/test_audit.py -m tier1

**Comment by ntkathole** [comment]
@jyejare This change is breaking hosts and audit tests from robottelo.

```
>               setattr(entity, field_name, attrs[field_name])
E               KeyError: 'user_data'
```
Please look into them.

**Comment by jyejare** [comment]
ok to test : tests/foreman/api/test_host.py tests/foreman/api/test_audit.py -m tier1

**Comment by jyejare** [comment]
ok to test : tests/foreman/api/test_host.py tests/foreman/api/test_audit.py -m tier1

**Comment by ntkathole** [comment]
ok to test : tests/foreman/api/test_host.py tests/foreman/api/test_audit.py -m tier1

**Comment by sghai** [comment]
Awesome @ntkathole

**Pull request merged**
