### PR TITLE
Reference bugs

### PR DESCRIPTION
**Pull request by Ichimonji10**
These bugs are all related to #115. I'm not done filing and linking to bugs, but this is a start.

### CODE REVIEW

**Comment by omaciel** [comment]
+1

**Comment by Ichimonji10** [comment]
I've fixed up this PR to satisfy Travis. I just needed to fix a bug reference and add a unit test.

**Comment by elyezer** [comment]
ACK

**Comment by JacobCallahan** [comment]
ACK

**Pull request merged**
