### PR TITLE
added support for the registration api command generation

### PR DESCRIPTION
**Pull request by omkarkhatavkar**
##### Description of changes
Adding the support the host registration command generation api 

##### Upstream API documentation, plugin, or feature links
https://<satellite_host>/apidoc/v2/registration_commands.html

##### Functional demonstration

Provide an execution of the modified code, with ipython code blocks or screen shots.
You can exercise the code as raw API calls or using any other method.

Your contribution should include updates to the unit tests, covering the modified portions or adding new coverage.

Example:
```
# Demonstrate functional Snapshot read in ipython
In [1]: from nailgun.entities import RegistrationCommand
In [2]: RegistrationCommand(activation_keys=[module_activation_key]).create()
Out [2]: {"registration_command": "curl -sS --insecure 'https://<satellite_host>/register?activation_keys=43&location_id=122&organization_id=121' -H 'Authorization: Bearer <token>' | bash")}
```

### CODE REVIEW

**Review by JacobCallahan — APPROVED** [review]

**Review by swadeley — APPROVED** [review]
ACK

**Comment by omkarkhatavkar** [comment]
@SatelliteQE/nailgun-tier-1-reviewers and @SatelliteQE/nailgun-tier-2-reviewers can we merge this ?

**Comment by jameerpathan111** [comment]
@omkarkhatavkar can you run code checks locally? Not sure why it's not running for nailgun again.
Refer: https://github.com/SatelliteQE/nailgun/pull/791#issuecomment-962954659

**Comment by omkarkhatavkar** [comment]
> @omkarkhatavkar can you run code checks locally? Not sure why it's not running for nailgun again. Refer: [#791 (comment)](https://github.com/SatelliteQE/nailgun/pull/791#issuecomment-962954659)

```
(env) /home/okhatavk/Satellite/nailgun (registration_command) $  pre-commit run --all-files
Reorder python imports...................................................Passed
pyupgrade................................................................Passed
black....................................................................Passed
Trim Trailing Whitespace.................................................Passed
Fix End of Files.........................................................Passed
Check Yaml...............................................................Passed
Debug Statements (Python)................................................Passed
(env) /home/okhatavk/Satellite/nailgun (registration_command) $ make test test-coverage
python -m unittest discover --start-directory tests --top-level-directory .
........../home/okhatavk/Satellite/nailgun/env/lib/python3.8/site-packages/packaging/version.py:111: DeprecationWarning: Creating a LegacyVersion has been deprecated and will be removed in the next major release
  warnings.warn(
...........................................................................................................................................................................................................................................................
----------------------------------------------------------------------
Ran 261 tests in 6.316s

OK
coverage run --source nailgun -m unittest discover --start-directory tests --top-level-directory .
........../home/okhatavk/Satellite/nailgun/env/lib/python3.8/site-packages/packaging/version.py:111: DeprecationWarning: Creating a LegacyVersion has been deprecated and will be removed in the next major release
  warnings.warn(
...........................................................................................................................................................................................................................................................
----------------------------------------------------------------------
Ran 261 tests in 6.752s

OK
(env) /home/okhatavk/Satellite/nailgun (registration_command) $ make docs-html docks-clean package package-clean 
make[1]: Entering directory `/home/okhatavk/Satellite/nailgun/docs'
sphinx-build -b html -d _build/doctrees  -W . _build/html
Running Sphinx v4.2.0
making output directory... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 15 source files that are out of date
updating environment: [new config] 15 added, 0 changed, 0 removed
reading sources... [100%] index                                                                                                                                              
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] index                                                                                                                                               
generating indices... genindex py-modindex done
writing additional pages... search done
copying static files... done
copying extra files... done
dumping search index in English (code: en)... done
dumping object inventory... done
build succeeded.

The HTML pages are in _build/html.

Build finished. The HTML pages are in _build/html.
make[1]: Leaving directory `/home/okhatavk/Satellite/nailgun/docs'
make: *** No rule to make target `docks-clean'.  Stop.
(env) /home/okhatavk/Satellite/nailgun (registration_command) $ make package package-clean 
./setup.py sdist bdist_wheel --universal
running sdist
running egg_info
creating nailgun.egg-info
writing nailgun.egg-info/PKG-INFO
writing dependency_links to nailgun.egg-info/dependency_links.txt
writing requirements to nailgun.egg-info/requires.txt
writing top-level names to nailgun.egg-info/top_level.txt
writing manifest file 'nailgun.egg-info/SOURCES.txt'
reading manifest file 'nailgun.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
adding license file 'LICENSE'
writing manifest file 'nailgun.egg-info/SOURCES.txt'
running check
creating nailgun-0.32.0
creating nailgun-0.32.0/nailgun
creating nailgun-0.32.0/nailgun.egg-info
copying files to nailgun-0.32.0...
copying LICENSE -> nailgun-0.32.0
copying MANIFEST.in -> nailgun-0.32.0
copying README.rst -> nailgun-0.32.0
copying VERSION -> nailgun-0.32.0
copying pyproject.toml -> nailgun-0.32.0
copying setup.py -> nailgun-0.32.0
copying nailgun/__init__.py -> nailgun-0.32.0/nailgun
copying nailgun/client.py -> nailgun-0.32.0/nailgun
copying nailgun/config.py -> nailgun-0.32.0/nailgun
copying nailgun/entities.py -> nailgun-0.32.0/nailgun
copying nailgun/entity_fields.py -> nailgun-0.32.0/nailgun
copying nailgun/entity_mixins.py -> nailgun-0.32.0/nailgun
copying nailgun.egg-info/PKG-INFO -> nailgun-0.32.0/nailgun.egg-info
copying nailgun.egg-info/SOURCES.txt -> nailgun-0.32.0/nailgun.egg-info
copying nailgun.egg-info/dependency_links.txt -> nailgun-0.32.0/nailgun.egg-info
copying nailgun.egg-info/requires.txt -> nailgun-0.32.0/nailgun.egg-info
copying nailgun.egg-info/top_level.txt -> nailgun-0.32.0/nailgun.egg-info
Writing nailgun-0.32.0/setup.cfg
creating dist
Creating tar archive
removing 'nailgun-0.32.0' (and everything under it)
running bdist_wheel
running build
running build_py
creating build
creating build/lib
creating build/lib/nailgun
copying nailgun/config.py -> build/lib/nailgun
copying nailgun/client.py -> build/lib/nailgun
copying nailgun/entity_mixins.py -> build/lib/nailgun
copying nailgun/__init__.py -> build/lib/nailgun
copying nailgun/entities.py -> build/lib/nailgun
copying nailgun/entity_fields.py -> build/lib/nailgun
installing to build/bdist.linux-x86_64/wheel
running install
running install_lib
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/wheel
creating build/bdist.linux-x86_64/wheel/nailgun
copying build/lib/nailgun/config.py -> build/bdist.linux-x86_64/wheel/nailgun
copying build/lib/nailgun/client.py -> build/bdist.linux-x86_64/wheel/nailgun
copying build/lib/nailgun/entity_mixins.py -> build/bdist.linux-x86_64/wheel/nailgun
copying build/lib/nailgun/__init__.py -> build/bdist.linux-x86_64/wheel/nailgun
copying build/lib/nailgun/entities.py -> build/bdist.linux-x86_64/wheel/nailgun
copying build/lib/nailgun/entity_fields.py -> build/bdist.linux-x86_64/wheel/nailgun
running install_egg_info
Copying nailgun.egg-info to build/bdist.linux-x86_64/wheel/nailgun-0.32.0-py3.8.egg-info
running install_scripts
adding license file "LICENSE" (matched pattern "LICEN[CS]E*")
creating build/bdist.linux-x86_64/wheel/nailgun-0.32.0.dist-info/WHEEL
creating 'dist/nailgun-0.32.0-py2.py3-none-any.whl' and adding 'build/bdist.linux-x86_64/wheel' to it
adding 'nailgun/__init__.py'
adding 'nailgun/client.py'
adding 'nailgun/config.py'
adding 'nailgun/entities.py'
adding 'nailgun/entity_fields.py'
adding 'nailgun/entity_mixins.py'
adding 'nailgun-0.32.0.dist-info/LICENSE'
adding 'nailgun-0.32.0.dist-info/METADATA'
adding 'nailgun-0.32.0.dist-info/WHEEL'
adding 'nailgun-0.32.0.dist-info/top_level.txt'
adding 'nailgun-0.32.0.dist-info/RECORD'
removing build/bdist.linux-x86_64/wheel
rm -rf build dist nailgun.egg-info
(env) /home/okhatavk/Satellite/nailgun (registration_command) $
```

**Review by jameerpathan111 — APPROVED** [review]

**Pull request merged**
