### PR TITLE
updated search mixin for various entities

### PR DESCRIPTION
**Pull request by sghai**
I need to this to validate and search some of the entities those are configured by default for configuring a hostgroup.

```
In [3]: arch = entities.Architecture(server_config).search(query={u'search': u'name="x86_64"'})
In [4]: arch[0].id
Out[4]: 1
```

```
In [5]: template1 = entities.ConfigTemplate(server_config).search(query={u'search': u'name="Satellite Kickstart Template"'})
In [6]: template1[0].id
Out[6]: 31
```

```
In [7]: domain = entities.Domain(server_config).search(query={u'search': u'name="idmqe.lab.eng.bos.redhat.com"'})
In [8]: domain[0].name
Out[8]: u'idmqe.lab.eng.bos.redhat.com'
```

```
In [9]: ptable = entities.PartitionTable(server_config).search(query={u'search': u'name="Kickstart default"'})
In [10]: ptable[0].id
Out[10]: 7
```

### CODE REVIEW

**Comment by Ichimonji10** [comment]
ACK

Thanks for the test results. The `search()` method does do some parsing of search results, and the results you've pasted show that it's able to parse real results with no problems.

**Comment by oshtaier** [comment]
ACK. You can use search without `query` keyword if you are working with default fields like `name`

**Comment by sghai** [comment]
@oshtaier : thanks. good to know. that helps to reduce some comments on next PR :)

**Comment by sghai** [comment]
```
In [8]: medium = entities.Media(server_config).search(query={u'search': u'name="Default_Organization/Library/RHEL67_x86_64"'})
In [9]: medium[0].id
Out[9]: 7
```

**Comment by sghai** [comment]
```
In [10]: proxy = entities.SmartProxy(server_config).search(query={u'search': u'name="cloud-qe-1.xxxxxxx"'})

In [11]: proxy[0].id
Out[11]: 1
```

**Comment by elyezer** [comment]
:+1:

**Pull request merged**
