### PR TITLE
Add bulk_add_subscriptions (#733)

### PR DESCRIPTION
**Pull request by swadeley**
Hello

I need to write test[1] which has to use `bulk/add_subscriptions` API. Therefore, need nailgun support for this API [2]

[1]  https://github.com/SatelliteQE/robottelo/blob/0d0bec299cad1d587e64b53cf48561aa3d4c46dd/tests/foreman/api/test_hostcollection.py#L383
[2] https://theforeman.org/plugins/katello/3.15/api/apidoc/v2/hosts_bulk_actions/add_subscriptions.html

### CODE REVIEW

**Comment by swadeley** [comment]
This is not working for me at present. I get error:
    `nailgun.entity_mixins.NoSuchPathError`

I will push my test code now for review.

**Comment by mirekdlugosz** [comment]
> This is not working for me at present. I get error:
> `nailgun.entity_mixins.NoSuchPathError`
> 
> I will push my test code now for review.

Were you able to solve this problem?

Can you add demonstration that this change works as intended (test result, custom script using new API, excerpt from interactive session)?

**Comment by swadeley** [comment]
> > This is not working for me at present. I get error:
> > `nailgun.entity_mixins.NoSuchPathError`
> > I will push my test code now for review.
> 
> Were you able to solve this problem?
> 
Hello @mirekdlugosz , yes, the error I mentioned in comment 1 was solved by adding the section starting:
`elif which in ('bulk/add_subscriptions',)
`
(currently L4268)

> Can you add demonstration that this change works as intended (test result, custom script using new API, excerpt from interactive session)?

Not yet, I need to add some VM creation and registration steps to my test (adding a subscription to a content host entry [can't be done it seems, need registered host](https://bugzilla.redhat.com/show_bug.cgi?id=1857124)).

Thank you

**Comment by swadeley** [comment]
robottelo]$ pytest  --show-capture=no tests/foreman/api/test_hostcollection.py -k test_positive_add_subscription 
=================================== test session starts ===============================================
platform linux -- Python 3.7.7, pytest-4.6.3, py-1.8.1, pluggy-0.13.1
shared_function enabled - OFF - scope:  - storage: file
rootdir: /sat6/robottelo
plugins: cov-2.8.1, services-1.3.1, mock-1.10.4, forked-1.1.3, ipdb-0.1, xdist-1.31.0
collecting ... 2020-07-30 18:46:43 - conftest - DEBUG - Collected 21 test cases
2020-07-30 19:46:45 - robottelo.ssh - DEBUG - Instantiated Paramiko client 0x7f281da90390
2020-07-30 19:46:45 - robottelo.ssh - INFO - Connected to [dhcp-2-190.vms.sat.rdu2.redhat.com]
2020-07-30 19:46:45 - robottelo.ssh - INFO - >>> rpm -q satellite
2020-07-30 19:46:46 - robottelo.ssh - INFO - <<< stdout
satellite-6.8.0-0.7.beta.el7sat.noarch

2020-07-30 19:46:46 - robottelo.ssh - DEBUG - Destroyed Paramiko client 0x7f281da90390
2020-07-30 19:46:46 - robottelo.host_info - DEBUG - Host Satellite version: 6.8
2020-07-30 19:46:46 - robottelo.helpers - DEBUG - Generated file bz_cache.json with BZ collect data
collected 21 items / 20 deselected / 1 selected                                                                  

tests/foreman/api/test_hostcollection.py .                                                                 [100%]

=========================== 1 passed, 20 deselected in 382.46 seconds ====================================

**Comment by swadeley** [comment]
Thank you

**Pull request merged**
