### PR TITLE
Added few extra fields for ContentView and Repository entities

### PR DESCRIPTION
**Pull request by abalakh**
Added few extra fields for ContentView and Repository entities, which will be used in upcoming robottelo PR.

### CODE REVIEW

**Comment by oshtaier** [comment]
Please, provide test result that you can able create `ContentView` and `Repository` entities (and, of course, read field data for them)

**Comment by abalakh** [comment]
@oshtaier i'll link robottelo PR as soon as it's ready (repos and cvs are created there and these fields are being used).

**Comment by oshtaier** [comment]
@abalakh You can show similar results like in #191 to be independent from any other PR

**Comment by abalakh** [comment]
@oshtaier it's pretty time consuming to manually create product, docker repo, sync it, create CV, add docker repo etc, so i'll better create CVs/repos with tests and then manually read them:
```python
>>> repo = entities.Repository(id=135).read()
>>> repo.content_counts
{u'puppet_module': 0, u'erratum': 0, u'package': 0, u'package_group': None, u'docker_tag': 5, u'rpm': 0, u'docker_image': 9}
>>> cv = entities.ContentView(id=88).read()
>>> cv.last_published
u'2015-09-02T11:30:24Z'
>>> cv.next_version
2
```

**Comment by oshtaier** [comment]
Fine:) ACK

**Comment by Ichimonji10** [comment]
The test results provided by SatelliteQE/robottelo#2726 are pretty convincing that this change works well. We may want to change `last_published` to a `DateField` or `DateTimeField` at some point, but this is a fine start. ACK.

**Pull request merged**
