### PR TITLE
Rename class DiscoveredHosts → DiscoveredHost

### PR DESCRIPTION
**Pull request by Ichimonji10**
Entities are named in the singular, not the plural.

### CODE REVIEW

**Comment by Ichimonji10** [comment]
I ran across this while typing up release notes. Robottelo makes no mention of the `DiscoveredHosts` class.

**Comment by Ichimonji10** [comment]
@sghai

**Comment by sthirugn** [comment]
ACK

**Comment by Ichimonji10** [comment]
Marking this as a prerequisite for the beta milestone because:

* this fix is simple, and
* it makes little sense to declare something as beta quality and then immediately rename one of the core classes in the very next release.

**Comment by sghai** [comment]
@Ichimonji10 : Thanks for making these changes. 

Also we can not create DiscoveredHost via `POST /api/v2/discovered_hosts` due to known bug. Currently, we can create 'Fake' DiscoveredHost only via upload facts. I'll add a test for this in robottelo. 

I'll see if I can discovered a host using libvirt with our automation boxes. Thanks.

**Comment by sghai** [comment]
ACK

**Comment by elyezer** [comment]
:+1:

**Comment by Ichimonji10** [comment]
Thanks for the info, @sghai.

**Pull request merged**
