### PR TITLE
Updated OS and ComputeAttribute entities

### PR DESCRIPTION
**Pull request by sghai**
- Updated 'ComputeAttribute' entity with 'create' and 'read' mixin
- Updated Operatingsystem entity to support search mixin

### CODE REVIEW

**Comment by oshtaier** [comment]
ACK pending test results (no matter where)

**Comment by sghai** [comment]
```
In [118]: entities.ComputeProfile(server_config, name='profile1').create()
Out[118]: nailgun.entities.ComputeProfile(nailgun.config.ServerConfig(url='https://foreman_server', verify=False, auth=('admin', 'changeme')), id=5, name=u'profile1')

In [119]: entities.LibvirtComputeResource(server_config, name='test2libvirt', provider='libvirt', url='qemu+tcp://foreman_server:16509/system', set_console_password=False,  location='4', organization='3').create()
Out[119]: nailgun.entities.LibvirtComputeResource(nailgun.config.ServerConfig(url='https://foreman_server', verify=False, auth=('admin', 'changeme')), description=None, url=u'qemu+tcp://foreman_server:16509/system', provider_friendly_name=u'Libvirt', location=[nailgun.entities.Location(nailgun.config.ServerConfig(url='https://foreman_server', verify=False, auth=('admin', 'changeme')), id=4)], provider=u'Libvirt', organization=[nailgun.entities.Organization(nailgun.config.ServerConfig(url='https://foreman_server', verify=False, auth=('admin', 'changeme')), id=3)], display_type=u'vnc', id=4, set_console_password=False, name=u'test2libvirt')

In [120]: entities.ComputeAttribute(server_config, compute_profile='5', compute_resource='4').create()
Out[120]: nailgun.entities.ComputeAttribute(nailgun.config.ServerConfig(url='https://foreman_server', verify=False, auth=('admin', 'changeme')), compute_profile=nailgun.entities.ComputeProfile(nailgun.config.ServerConfig(url='https://foreman_server', verify=False, auth=('admin', 'changeme')), id=5), id=1, compute_resource=nailgun.entities.AbstractComputeResource(nailgun.config.ServerConfig(url='https://foreman_server', verify=False, auth=('admin', 'changeme')), id=4))

```

**Comment by sghai** [comment]
```
In [130]: os = entities.OperatingSystem(server_config).search(query={u'search': u'name="RedHat" AND major="6" AND minor="7"'})
In [131]: os
Out[131]: [nailgun.entities.OperatingSystem(nailgun.config.ServerConfig(url='https://foreman_server', verify=False, auth=('admin', 'changeme')), major=u'6', family=u'Redhat', name=u'RedHat', release_name=None, id=1, minor=u'7', description=u'RedHat 6.7')]
```

**Comment by Ichimonji10** [comment]
Looks like `read()` finds and parses the `config_template` attribute correctly.

```python
>>> from nailgun import entities
>>> os = entities.OperatingSystem(id=1).read()
>>> len(os.config_template)
5
>>> type(os.config_template[0])
<class 'nailgun.entities.ConfigTemplate'>
```

ACK.

**Comment by elyezer** [comment]
:+1:

**Pull request merged**
