### PR TITLE
Use method `ServerConfig.get_client_kwargs`

### PR DESCRIPTION
**Pull request by Ichimonji10**
Why use this method? From the method docstring:

> This method returns a dict of attributes that can be unpacked and used as
> kwargs via the ``**`` operator. For example::
>
>     cfg = ServerConfig.get()
>     client.get(cfg.url + '/api/v2', **cfg.get_client_kwargs())
>
> This method is useful because client code may not know which attributes should
> be passed from a ``ServerConfig`` object to one of the ``nailgun.client``
> functions. Consider that the example above could also be written like this::
>
>     cfg = ServerConfig.get()
>     client.get(cfg.url + '/api/v2', auth=cfg.auth, verify=cfg.verify)
>
> But this latter approach is more fragile. It will break if ``cfg`` does not
> have an ``auth`` or ``verify`` attribute.

In other words, using `get_client_kwargs` is more robust than passing individual
`ServerConfig` object attributes to the various functions in `nailgun.client`.

Test results against a downstream system:

    $ nosetests tests/foreman/api/test_multiple_paths.py
    ...S...S......S...............................................................S...S..........................................................................................................................................SSS..S.S.SSSSSS.S..SS.SSSSSSSSSSSSSSSSSSSSSSSSSSSS
    ----------------------------------------------------------------------
    Ran 271 tests in 459.591s

    OK (SKIP=47)

### CODE REVIEW

**Comment by omaciel** [comment]
APT

**Comment by elyezer** [comment]
ACK, pending rebase.

**Comment by Ichimonji10** [comment]
Rebased.

**Comment by elyezer** [comment]
APT

**Comment by elyezer** [comment]
Travis is green and coveralls does not look to be running this. Will merge.

**Pull request merged**
