### PR TITLE
Normalize Helper Methods

### LINKED ISSUE #41: Review entity methods
Several methods in module `nailgun.entities` do not map nicely to an underlying path. <ins>In addition, several methods do not have appropriate arguments.</ins> The methods exposed by the entity classes should be reviewed to make sure that they are appropriately named and placed on the most appropriate class.

Methods to review:

* [x] `ActivationKey.add_subscriptions`
* [x] `ActivationKey.content_override`
* [x] `AbstractDockerContainer.power`
* [x] `AbstractDockerContainer.logs`
* [x] `ContentViewVersion.promote`
* [x] `ContentView.publish`
* [x] `ContentView.set_repository_ids`
* [x] ~~`ContentView.available_puppet_modules`~~
* [x] `ContentView.add_puppet_module`
* [x] `ContentView.copy`
* [x] ~~`ForemanTask.poll`~~
* [x] `Organization.subscriptions`
* [x] `Organization.upload_manifest`
* [x] `Organization.delete_manifest`
* [x] `Organization.refresh_manifest`
* [x] `Organization.sync_plan`
* [x] ~~`Organization.list_rhproducts`~~ (EntitySearchMixin is used instead)
* [x] ~~`Permission.search`~~ (EntitySearchMixin is used instead)
* [x] `Product.list_repositorysets`
* [x] ~~`Product.fetch_rhproduct_id`~~ (EntitySearchMixin is used instead)
* [x] ~~`Product.fetch_reposet_id`~~ (EntitySearchMixin is used instead)
* [x] `Product.enable_rhrepo`
* [x] `Product.disable_rhrepo`
* [x] `Repository.sync`
* [x] ~~`Repository.fetch_repoid`~~ (EntitySearchMixin is used instead)
* [x] `Repository.upload_content`
* [x] `RHCIDeployment.add_hypervisors`
* [x] `RHCIDeployment.deploy`
* [x] `SyncPlan.add_products`
* [x] `SyncPlan.remove_products`

One example of an entity method that does not map nicely to an underlying path is [`Organization.upload_manifest`](http://nailgun.readthedocs.org/en/latest/api/nailgun.html#nailgun.entities.Organization.upload_manifest). This method POSTs to the following path:

    /katello/api/v2/organizations/<organization_id>/subscriptions/upload

However, the API documentation lists a second API path that can also be POSTed to:

    /katello/api/v2/subscriptions/upload

The latter approach is preferred. The method `Organization.upload_manifest` is not clearly related to any underlying path, but the method `Subscription.upload` is. There are also a bevy of problems with nested paths: they make it hard to determine what the canonical location of a resource it, it promotes a proliferation of the size of the API, and it makes it hard to manage special-case logic. (Special case logic is more easily managed when building a JSON payload than when building a URL.) Thus, `Organization.upload_manifest` should be dropped in favor of `Subscription.upload`. It could look like this:

```python
def upload(
        self, content, organization_id, repository_url=None,
        synchronous=True):
    """Upload a subscription manifest file.

    :param content: A file handle to a manifest file. In other words,
        the object returned by `open('path/to/file', 'rb')`.
    :param int organization_id: An organization ID.
    :param str repository_url: An optional repository URL.
    :param bool synchronous: What should happen if the server returns an
        HTTP 202 (accepted) status code? Wait for the task to complete if
        ``True``. Immediately return JSON response otherwise.
    :returns: The server's response, with all JSON decoded.
    :rtype: dict
    :raises: ``nailgun.entity_mixins.TaskTimedOutError`` if an HTTP 202
        response is received, ``synchronous is True`` and the task
        completes with any result other than "success".

    """
    data = {'organization_id': organization_id}
    if repository_url is not None:
        data['repository_url'] = repository_url
    response = client.post(
        self.path('upload'),
        data,
        auth=self._server_config.auth,
        files={'content': content},
        verify=self._server_config.verify,
    )
    response.raise_for_status()

    # Poll a task if necessary, then return the JSON response.
    if synchronous is True and response.status_code == httplib.ACCEPTED:
        return ForemanTask(
            self._server_config,
            id=response.json()['id']
        ).poll()
    return response.json()
```

### PR DESCRIPTION
**Pull request by Ichimonji10**
<ins>What follows is the contents  of the third commit message.</ins>

Fix #41:

> Several methods in module `nailgun.entities` do not map nicely to an
> underlying path. In addition, several methods do not have appropriate
> arguments. The methods exposed by the entity classes should be reviewed to
> make sure that they are appropriately named and placed on the most appropriate
> class.

Though many actions can be performed with the mixins, some do not map nicely to
one of the CRUD verbs. For example, publishing a content view or uploading
content to a repository are actions that cannot be described by the CRUD verbs.

NailGun must be able to carry out actions such as publishing or uploading. But
how? NailGun has thus far addressed these needs by simply adding methods on an
ad-hoc basis. This works, but it comes with costs:

* The helper methods must be learned one-by-one, as there is no guarantee of
  consistency among them.
* Some helper methods will require ongoing maintenance. For example, the
  `AbstractDockerContainer.power` method only accepts the strings "start,"
  "stop" and "status," and it will need to be updated when Satellite changes.
  NailGun already commits to creating entity classes for each resource and
  describing each available field — describing the logic of each helper method
  raises the cost of maintenance even higher.

Address these issues. Give each helper method a highly similar signature. Do not
attempt to interpret the messages sent from clients to the server, but instead
let the server validate the contents of each message.

The previous two commits in this chain of commits already make some head-way on
this front. This commit makes the following changes:

* Add the `Subscription` entity.
* Change the signature of `ActivationKey.content_override`.
* Change the signature of `Repository.upload_content`.
* Drop `ContentView.add_puppet_module`. (Use `ContentViewPuppetModule.create`
  instead.)
* Drop `ContentView.set_repository_ids`. (Use `ContentView.update` instead.)
* Drop `Organization.delete_manifest`. (Use `Subscription.delete_manifest`
  instead.)
* Drop `Organization.refresh_manifest`. (Use `Subscription.refresh_manifest`
  instead.)
* Drop `Organization.subscriptions`. (Use `Subscription.search` instead.)
* Drop `Organization.sync_plan`. (Use `SyncPlan.create` instead.)
* Drop `Organization.upload_manifest`. (Use `Subscription.upload` instead.)
* Drop `RHCIDeployment.add_hypervisors`. (Use RHCIDeployment.update` instead.)
* Drop `RepositorySet.list_all`. (Use `RepositorySet.search` instead.)
* Update unit tests.

Some of these methods may be re-added in some form or another. For example, it
would be useful to add a helper method `Organization.subscriptions_upload` that
maps to the `/katello/api/v2/organizations/:id/subscriptions/upload` path.
However, at this point in time, the focus is on making NailGun's API stable.
Developers should be able to write code against NailGun and be confident that it
will not break. These changes add stability, and future changes may build upon
them.

### CODE REVIEW

**Comment by Ichimonji10** [comment]
The third commit makes the following changes:

* Add the `Subscription` entity.
* Change the signature of `ActivationKey.content_override`.
* Change the signature of `Repository.upload_content`.
* Drop `ContentView.add_puppet_module`. (Use `ContentViewPuppetModule.create`
  instead.)
* Drop `ContentView.set_repository_ids`. (Use `ContentView.update` instead.)
* Drop `Organization.delete_manifest`. (Use `Subscription.delete_manifest`
  instead.)
* Drop `Organization.refresh_manifest`. (Use `Subscription.refresh_manifest`
  instead.)
* Drop `Organization.subscriptions`. (Use `Subscription.search` instead.)
* Drop `Organization.sync_plan`. (Use `SyncPlan.create` instead.)
* Drop `Organization.upload_manifest`. (Use `Subscription.upload` instead.)
* Drop `RHCIDeployment.add_hypervisors`. (Use RHCIDeployment.update` instead.)
* Drop `RepositorySet.list_all`. (Use `RepositorySet.search` instead.)
* Update unit tests.

Some of these methods may be re-added in some form or another. For example, it
would be useful to add a helper method `Organization.subscriptions_upload` that
maps to the `/katello/api/v2/organizations/:id/subscriptions/upload` path.
However, at this point in time, the focus is on making NailGun's API stable.
Developers should be able to write code against NailGun and be confident that it
will not break. These changes add stability, and future changes may build upon
them.

**Comment by Ichimonji10** [comment]
```
$ coverage report
Name                    Stmts   Miss  Cover
-------------------------------------------
nailgun/__init__            3      0   100%
nailgun/client             79      9    89%
nailgun/config             83     12    86%
nailgun/entities          877     13    99%
nailgun/entity_fields      79      0   100%
nailgun/entity_mixins     266      5    98%
-------------------------------------------
TOTAL                    1387     39    97%
```

:tada:

**Comment by elyezer** [comment]
We are almost 100% test coverage :tada:

**Comment by elyezer** [comment]
ACK

**Comment by oshtaier** [comment]
Seems really nice. Thank @Ichimonji10 for your hard work! :+1: 
ACK

**Comment by oshtaier** [comment]
Feel free to merge at any time. Just maybe someone else interested in review

**Comment by Ichimonji10** [comment]
Many thanks to @oshtaier, @elyezer, @abalakh and others for helping me to tackle #41. You've given feedback on the relevant github issues, made pull requests here, made corresponding pull requests in SatelliteQE/robottelo, put up with my lengthy review process and more. I appreciate it.

**Comment by sthirugn** [comment]
ACK - Great work all of you!

**Pull request merged**
