### PR TITLE
Added a new field root_pass to hostgroup entity

### PR DESCRIPTION
**Pull request by sghai**
```console
In [5]: hg = HostGroup(server_config, name='testpass14', root_pass='test@1234').create()

In [6]: hg
Out[6]: nailgun.entities.HostGroup(nailgun.config.ServerConfig(url='SERVER', verify=False, auth=('admin', 'changeme')), domain=None, medium=None, parent=None, ptable=None, content_source=None, lifecycle_environment=None, operatingsystem=None, name=u'testpass14', subnet=None, puppet_proxy=None, realm=None, content_view=None, id=46, environment=None, location=[], organization=[], puppet_ca_proxy=None, architecture=None)
```

### CODE REVIEW

**Comment by oshtaier** [comment]
ACK. As far as I see we don't need any unit tests for that small update

**Comment by sghai** [comment]
Yeah.. no unit tests are required. Please see if we can merge it quickly.

**Comment by rochacbruno** [comment]
ACK

**Comment by abalakh** [comment]
@sghai @oshtaier we could update `test_ignore_arg_v1` test [here](https://github.com/SatelliteQE/nailgun/blob/master/tests/test_entities.py#L989)

**Comment by oshtaier** [comment]
Missed that. Thanks

**Comment by sghai** [comment]
@abalakh @oshtaier : will raise a PR to update the test.

**Pull request merged**
