### PR TITLE
Updated Bookmark class:

### PR DESCRIPTION
**Pull request by rplevka**
- included mixins to support CRUDS operations

### CODE REVIEW

**Comment by rplevka** [comment]
I included the other mixins to support the following operations on Bookmarks:

```python
In [1]: from nailgun import entities
In [2]: a = entities.Bookmark(name='foo',query='bar',public='true',controller='architectures').create()

In [3]: a
Out[3]: nailgun.entities.Bookmark(nailgun.config.ServerConfig(url=u'https://<FQDN>', verify=False, auth=(u'admin', u'changeme')), public=True, controller=u'architectures', query=u'bar', id=1363, name=u'foo')

In [4]: entities.Bookmark(id=1363).read()
Out[4]: nailgun.entities.Bookmark(nailgun.config.ServerConfig(url=u'https://<FQDN>', verify=False, auth=(u'admin', u'changeme')), public=True, controller=u'architectures', query=u'bar', id=1363, name=u'foo')

In [5]: entities.Bookmark(id=1363, query='baz').update()
Out[5]: nailgun.entities.Bookmark(nailgun.config.ServerConfig(url=u'https://<FQDN>', verify=False, auth=(u'admin', u'changeme')), public=True, controller=u'architectures', query=u'baz', id=1363, name=u'foo')

In [5]: entities.Bookmark().search(query={'search': 'name="foo"'})
Out[5]: [nailgun.entities.Bookmark(nailgun.config.ServerConfig(url=u'https://<FQDN>', verify=False, auth=(u'admin', u'changeme')), id=1363, controller=u'architectures', query=u'baz', public=True, name=u'foo')]

In [6]: entities.Bookmark(id=1363).delete()
Out[6]: 
{u'controller': u'architectures',
 u'id': 1363,
 u'name': u'foo',
 u'owner_id': 3,
 u'owner_type': u'User',
 u'public': True,
 u'query': u'baz'}

In [7]: entities.Bookmark().search(query={'search': 'name="foo"'})
Out[7]: []
```

**Comment by omaciel** [comment]
@rplevka assuming you don't have to add entity to our existing tests (please check?), ACK

**Comment by rplevka** [comment]
@omaciel, checked, it does not seem to be used anywhere yet:


```bash
$ git grep -i bookmark ~/work/robottelo/tests/foreman/api
$
```

**Comment by oshtaier** [comment]
Not sure that understand @omaciel question, but anyway ACK

**Comment by omaciel** [comment]
@oshtaier I meant that we don't seem to have tests for `Bookmark` except for `test_init_succeeds`. I'd like to see tests added to ``class PathTestCase``, ``class SearchRawTestCase``, etc.

**Comment by oshtaier** [comment]
ah, you meant unit tests.
@rplevka Please, check if you need to add any.

**Comment by omaciel** [comment]
@oshtaier he does :) there's one 1 test afaik

**Comment by oshtaier** [comment]
hmm. I don't see any unit tests in that PR. Probably, we are looking into different ones =)

**Comment by omaciel** [comment]
@oshtaier I'm asking @rplevka to provide tests, since there's none yet :)

**Comment by oshtaier** [comment]
got it

**Comment by rplevka** [comment]
@omaciel, API tests utilizing `nailgun.entities.Bookmark` are coming soon :)
I planned to submit non-test code as a separate PR. Would you want me to do it in a single one?

**Comment by omaciel** [comment]
@rplevka I would and it should be pretty easy to do it too :)

**Comment by oshtaier** [comment]
@rplevka Any updates?

**Comment by Ichimonji10** [comment]
I don't think we need any extra unit tests for this commit. There's already thorough set of unit tests for the methods provided by `nailgun.entity_mixins`, and the test cases like `SearchRawTestCase` and `ReadTestCase` are intended to show that non-inherited methods don't break anything. The bookmark entity has only one non-inherited method, `Bookmark.__init__`, which is tested by `InitTestCase.test_init_succeeds`.

The most useful proof of correctness here would be some test results against a live Satellite system. (Remember that you can use `cd my/robottelo/repo && pip install --editable my/nailgun/repo` to install your custom version of Nailgun.)

**Comment by omaciel** [comment]
OK, I trust @Ichimonji10 comment here, so I'll go ahead and merge this puppy.

**Pull request merged**
