### PR TITLE
Release 0.32.0

### PR DESCRIPTION
**Pull request by sean797**
Is everyone is happy to do a release? Doing this in place of https://github.com/theforeman/foreman-ansible-modules/pull/245

Whoever merges this needs to create and push a tag, then create a release in GitHub. I'm happy to do it if no else wants to.

### CODE REVIEW

**Comment by ogajduse** [comment]
I am open to this. But I will leave the decision up to the others.

**Comment by ogajduse** [comment]
What do you think about the release @san7ket? Asking you as a maintainer, I'm not sure which other reviewers I should mention here.

**Comment by jhutar** [comment]
Also tagging other tier2 reviewers here: @abalakh @ldjebran @jyejare @oshtaier as this is important for other team.

**Comment by san7ket** [comment]
I am good for release, but I would really like we focus on [1] after this release and make this last release form Master branch 

https://github.com/SatelliteQE/nailgun/issues/581

**Comment by jhutar** [comment]
Hello @abalakh @ldjebran @jyejare @oshtaier. Still one more reviewer is needed.

**Comment by JacobCallahan** [comment]
ACK

**Pull request merged**
