### PR TITLE
Add vm_attributes to compute_attribute

### PR DESCRIPTION
**Pull request by bagasse**
* Depends on [Fixes #25975 - Add ability to read compute_attributes via foreman API](https://github.com/theforeman/foreman/pull/6457)
* Needed by [Add compute_attributes support to foreman-ansible-modules #222](https://github.com/theforeman/foreman-ansible-modules/issues/222)

### CODE REVIEW

**Comment by oshtaier** [comment]
Looks good, but console output for added functionality is required. Like:
>>entities.ComputeAttribute(...).update(...)
>>entities.ComputeAttribute(...).search(...)
Just to prove that API endpoint are really present in the application under test

**Comment by bagasse** [comment]
@oshtaier, sure :)
```
>>> from nailgun import entity_mixins, entity_fields, entities
>>> from nailgun.config import ServerConfig
>>> from nailgun.entities import Entity, ComputeProfile, ComputeAttribute, Location, Organization, Domain
>>> entity_mixins.DEFAULT_SERVER_CONFIG = ServerConfig(url='https://foreman.example.com', verify=False, auth=('xxxxxxxxx','xxxxxxxxxxxxx'))
>>> cp1 = ComputeProfile(id=1).read()
>>> cp1
nailgun.entities.ComputeProfile(name='1-Small', compute_attribute=[nailgun.entities.ComputeAttribute(id=1)], id=1)
>>> ca1 = ComputeAttribute(id=1).read()
>>> ca1
nailgun.entities.ComputeAttribute(compute_profile=nailgun.entities.ComputeProfile(id=1), compute_resource=nailgun.entities.AbstractComputeResource(id=2), vm_attrs={'cluster': 'c95c55f3-705e-4182-92a6-f66754aadf02', 'template': '', 'instance_type': 'f7fcedcc-bdae-43e6-8edc-bb5a6bd652fa', 'cores': '2', 'sockets': '1', 'memory': '2147483648', 'ha': '1'}, attributes={'cores': '2', 'interfaces_attributes': {}, 'memory': '2147483648', 'cluster_id': 'c95c55f3-705e-4182-92a6-f66754aadf02', 'cluster_name': 'DevSandbox', 'template_id': '', 'template_name': None, 'volumes_attributes': {}}, id=1)
>>> cas = ComputeAttribute().search(set(), {'search': 'compute_profile="{}"'.format('1-Small')})
>>> cas
[nailgun.entities.ComputeAttribute(compute_profile=nailgun.entities.ComputeProfile(id=1), compute_resource=nailgun.entities.AbstractComputeResource(id=2), vm_attrs={'cluster': 'c95c55f3-705e-4182-92a6-f66754aadf02', 'template': '', 'instance_type': 'f7fcedcc-bdae-43e6-8edc-bb5a6bd652fa', 'cores': '2', 'sockets': '1', 'memory': '2147483648', 'ha': '1'}, attributes={'cores': '2', 'interfaces_attributes': {}, 'memory': '2147483648', 'cluster_id': 'c95c55f3-705e-4182-92a6-f66754aadf02', 'cluster_name': 'DevSandbox', 'template_id': '', 'template_name': None, 'volumes_attributes': {}}, id=1)]
>>> ca1.vm_attrs
{'cluster': 'c95c55f3-705e-4182-92a6-f66754aadf02', 'template': '', 'instance_type': 'f7fcedcc-bdae-43e6-8edc-bb5a6bd652fa', 'cores': '2', 'sockets': '1', 'memory': '2147483648', 'ha': '1'}
>>> ca1.vm_attrs['cores'] = 4
>>> ca1.update()
nailgun.entities.ComputeAttribute(compute_profile=nailgun.entities.ComputeProfile(id=1), compute_resource=nailgun.entities.AbstractComputeResource(id=2), vm_attrs={'cluster': 'c95c55f3-705e-4182-92a6-f66754aadf02', 'template': '', 'instance_type': 'f7fcedcc-bdae-43e6-8edc-bb5a6bd652fa', 'cores': 4, 'sockets': '1', 'memory': '2147483648', 'ha': '1'}, attributes={'cores': 4, 'interfaces_attributes': {}, 'memory': '2147483648', 'cluster_id': 'c95c55f3-705e-4182-92a6-f66754aadf02', 'cluster_name': 'DevSandbox', 'template_id': '', 'template_name': None, 'volumes_attributes': {}}, id=1)
>>> ca1.read()
nailgun.entities.ComputeAttribute(compute_profile=nailgun.entities.ComputeProfile(id=1), compute_resource=nailgun.entities.AbstractComputeResource(id=2), vm_attrs={'cluster': 'c95c55f3-705e-4182-92a6-f66754aadf02', 'template': '', 'instance_type': 'f7fcedcc-bdae-43e6-8edc-bb5a6bd652fa', 'cores': 4, 'sockets': '1', 'memory': '2147483648', 'ha': '1'}, attributes={'cores': 4, 'interfaces_attributes': {}, 'memory': '2147483648', 'cluster_id': 'c95c55f3-705e-4182-92a6-f66754aadf02', 'cluster_name': 'DevSandbox', 'template_id': '', 'template_name': None, 'volumes_attributes': {}}, id=1)
>>>
```

**Comment by bagasse** [comment]
* I already make a search in the previous comment, I copied it below: 
```
>>> cas = ComputeAttribute().search(set(), {'search': 'compute_profile="{}"'.format('1-Small')})
>>> cas
[nailgun.entities.ComputeAttribute(compute_profile=nailgun.entities.ComputeProfile(id=1), compute_resource=nailgun.entities.AbstractComputeResource(id=2), vm_attrs={'cluster': 'c95c55f3-705e-4182-92a6-f66754aadf02', 'template': '', 'instance_type': 'f7fcedcc-bdae-43e6-8edc-bb5a6bd652fa', 'cores': '2', 'sockets': '1', 'memory': '2147483648', 'ha': '1'}, attributes={'cores': '2', 'interfaces_attributes': {}, 'memory': '2147483648', 'cluster_id': 'c95c55f3-705e-4182-92a6-f66754aadf02', 'cluster_name': 'DevSandbox', 'template_id': '', 'template_name': None, 'volumes_attributes': {}}, id=1)]
```

* Here added a search with non existant value
```
>>> cas = ComputeAttribute().search(set(), {'search': 'compute_profile="{}"'.format('doesntexist')})
>>> cas
[]
>>>
```
* Here added multi-criteria search with both valid param
```
>>> cas = ComputeAttribute().search(set(), {'search': 'compute_profile="1-Small" and compute_resource="ovirt-cr01"'})
>>> cas
[nailgun.entities.ComputeAttribute(compute_profile=nailgun.entities.ComputeProfile(id=1), compute_resource=nailgun.entities.AbstractComputeResource(id=2), vm_attrs={'cluster': 'c95c55f3-705e-4182-92a6-f66754aadf02', 'template': '', 'instance_type': 'f7fcedcc-bdae-43e6-8edc-bb5a6bd652fa', 'cores': 4, 'sockets': '1', 'memory': '2147483648', 'ha': '1'}, attributes={'cores': 4, 'interfaces_attributes': {}, 'memory': '2147483648', 'cluster_id': 'c95c55f3-705e-4182-92a6-f66754aadf02', 'cluster_name': 'DevSandbox', 'template_id': '', 'template_name': None, 'volumes_attributes': {}}, id=1)]
```
* Here added search with one valid param and other non existant
```
>>> cas = ComputeAttribute().search(set(), {'search': 'compute_profile="1-Small" and compute_resource="ovirt-cr0"'})
>>> cas
[]
>>>
```

* I already make an update on attributes of ComputeAttribute (update 'cores' from 2 to 4), then read, I copied it below:
```
>>> ca1.vm_attrs
{'cluster': 'c95c55f3-705e-4182-92a6-f66754aadf02', 'template': '', 'instance_type': 'f7fcedcc-bdae-43e6-8edc-bb5a6bd652fa', 'cores': '2', 'sockets': '1', 'memory': '2147483648', 'ha': '1'}
>>> ca1.vm_attrs['cores'] = 4
>>> ca1.update()
nailgun.entities.ComputeAttribute(compute_profile=nailgun.entities.ComputeProfile(id=1), compute_resource=nailgun.entities.AbstractComputeResource(id=2), vm_attrs={'cluster': 'c95c55f3-705e-4182-92a6-f66754aadf02', 'template': '', 'instance_type': 'f7fcedcc-bdae-43e6-8edc-bb5a6bd652fa', 'cores': 4, 'sockets': '1', 'memory': '2147483648', 'ha': '1'}, attributes={'cores': 4, 'interfaces_attributes': {}, 'memory': '2147483648', 'cluster_id': 'c95c55f3-705e-4182-92a6-f66754aadf02', 'cluster_name': 'DevSandbox', 'template_id': '', 'template_name': None, 'volumes_attributes': {}}, id=1)
>>> ca1.read()
nailgun.entities.ComputeAttribute(compute_profile=nailgun.entities.ComputeProfile(id=1), compute_resource=nailgun.entities.AbstractComputeResource(id=2), vm_attrs={'cluster': 'c95c55f3-705e-4182-92a6-f66754aadf02', 'template': '', 'instance_type': 'f7fcedcc-bdae-43e6-8edc-bb5a6bd652fa', 'cores': 4, 'sockets': '1', 'memory': '2147483648', 'ha': '1'}, attributes={'cores': 4, 'interfaces_attributes': {}, 'memory': '2147483648', 'cluster_id': 'c95c55f3-705e-4182-92a6-f66754aadf02', 'cluster_name': 'DevSandbox', 'template_id': '', 'template_name': None, 'volumes_attributes': {}}, id=1)
>>>
```

If you want any other tests, please feel free to ask. Thanks for your review :)

**Comment by bagasse** [comment]
@mirzal, this is waiting for [foreman pr#6457](https://github.com/theforeman/foreman/pull/6457).

@mirzal , @oshtaier thank you for your (very) quick reviews :)

**Comment by bagasse** [comment]
@mirzal, the  [foreman pr#6457](https://github.com/theforeman/foreman/pull/6457) is now merged ! :)

**Comment by mirzal** [comment]
Yeah, just saw notification. Thanks for shout out :) .

**Pull request merged**
