### PR TITLE
Added `date_type` field to ContentViewFilterRule entity and updated default login for User

### PR DESCRIPTION
**Pull request by abalakh**
```python
In [5]: entities.ContentViewFilterRule(content_view_filter=109, date_type='issue
   ...: d', end_date='2017-06-26', start_date='2017-06-21').create()
2017-06-21 17:26:06 - nailgun.client - DEBUG - Making HTTP POST request to https://example.com/katello/api/v2/content_view_filters/109/rules with options {'verify': False, 'auth': ('admin', '*********'), 'headers': {'content-type': 'application/json'}} and data {"end_date": "2017-06-26", "content_view_filter_id": 109, "date_type": "issued", "start_date": "2017-06-21"}.
2017-06-21 17:26:07 - nailgun.client - DEBUG - Received HTTP 200 response:   {"content_view_filter_id":109,"start_date":"2017-06-21","end_date":"2017-06-26","types":["bugfix","enhancement","security"],"date_type":"issued","id":18,"created_at":"2017-06-21 14:26:07 UTC","updated_at":"2017-06-21 14:26:07 UTC"}

Out[5]: nailgun.entities.ContentViewFilterRule(end_date=u'2017-06-26', date_type=u'issued', start_date=u'2017-06-21', content_view_filter=nailgun.entities.AbstractContentViewFilter(id=109), id=18, types=[u'bugfix', u'enhancement', u'security'])

In [6]: entities.ContentViewFilterRule(id=18, content_view_filter=109).read().da
   ...: te_type
2017-06-21 17:26:52 - nailgun.client - DEBUG - Making HTTP GET request to https://example.com/katello/api/v2/content_view_filters/109/rules/18 with options {'verify': False, 'auth': ('admin', '*********'), 'headers': {'content-type': 'application/json'}} and no data.
2017-06-21 17:26:54 - nailgun.client - DEBUG - Received HTTP 200 response:   {"content_view_filter_id":109,"start_date":"2017-06-21","end_date":"2017-06-26","types":["bugfix","enhancement","security"],"date_type":"issued","id":18,"created_at":"2017-06-21 14:26:07 UTC","updated_at":"2017-06-21 14:26:07 UTC"}

Out[6]: u'issued'
```

### CODE REVIEW

**Comment by oshtaier** [comment]
Do we have changes for login field requirements? Or why do we change it?

**Comment by abalakh** [comment]
@oshtaier it's default value which is set if user hasn't specified any. Similar to all the rest entities - it's hard to debug having entity name of 100 hieroglyph chars, especially when you need to input it to successfully login :)

**Comment by oshtaier** [comment]
ACK in case we don't need all these types for login

**Comment by abalakh** [comment]
Basically, this change is supposed to be a part of #290 and SatelliteQE/robottelo#2521 . We aren't removing the ability to create user with special chars in login, we just change a framework to create readable logins if user hasn't explicitly specified other.

**Comment by oshtaier** [comment]
ACK

**Pull request merged**
