### PR TITLE
Update CommonParameter entity.

### PR DESCRIPTION
**Pull request by svtkachenko**
```
In [6]: entities.CommonParameter(server_config).create(create_missing=True)
Out[6]: nailgun.entities.CommonParameter(id=39, value=u'\ud1da\U00026556\u421e\u971f\U000276b9\u4bb7\u65e3\U00013128\U00021728\U0002b298\U00025db9\U000132be\u677e\uc984\u1d6b', name=u'\u780e\u3d73')

In [7]: entities.CommonParameter(server_config, id=39).read()
Out[7]: nailgun.entities.CommonParameter(id=39, value=u'\ud1da\U00026556\u421e\u971f\U000276b9\u4bb7\u65e3\U00013128\U00021728\U0002b298\U00025db9\U000132be\u677e\uc984\u1d6b', name=u'\u780e\u3d73')

In [12]: a = entities.CommonParameter(server_config, name='qwerty', value='123').create(create_missing=True)

In [13]: a.name = 'ytrewq'

In [14]: a.update(['name'])
Out[14]: nailgun.entities.CommonParameter(id=40, value=u'123', name=u'ytrewq')

In [16]: a.delete()
Out[16]: 
{u'created_at': u'2017-05-30T15:00:46.720Z',
 u'hidden_value': u'*****',
 u'id': 40,
 u'name': u'ytrewq',
 u'priority': 0,
 u'reference_id': None,
 u'updated_at': u'2017-05-30T15:01:12.040Z',
 u'value': u'123'}

In [19]: entities.CommonParameter(server_config).search(query={'search': 'name=qwerty'})
Out[19]: [nailgun.entities.CommonParameter(id=41, value=u'123', name=u'qwerty')]
```

### CODE REVIEW

**Comment by svtkachenko** [comment]
1. 
```
In [5]: entities.CommonParameter(server_config, id=42).read()
Out[5]: nailgun.entities.CommonParameter(id=42, value=u'\U0002363a\ufaa6\U00025d0a\U00021766\U000248b6\U00025477\ud1ff\U000267db\u8ad8d\U0002164f\U0002b430\U00023f3c\ub5f3\U000298d4\ubbd9\u0e43\U00024fe7\U000247bd\ub1ca\U00025faa\u9079\ud0a5\u9e45\u4e79\u9edb\U000229d3\U00029614\U0002902d', name=u'\u4d0b')

In [6]: entities.CommonParameter(server_config, id=42).delete()
Out[6]: 
{u'created_at': u'2017-05-31T06:39:03.731Z',
 u'hidden_value': u'*****',
 u'id': 42,
 u'name': u'\u4d0b',
 u'priority': 0,
 u'reference_id': None,
 u'updated_at': u'2017-05-31T06:39:03.731Z',
 u'value': u'\U0002363a\ufaa6\U00025d0a\U00021766\U000248b6\U00025477\ud1ff\U000267db\u8ad8d\U0002164f\U0002b430\U00023f3c\ub5f3\U000298d4\ubbd9\u0e43\U00024fe7\U000247bd\ub1ca\U00025faa\u9079\ud0a5\u9e45\u4e79\u9edb\U000229d3\U00029614\U0002902d'}

In [7]: entities.CommonParameter(server_config, id=42).read()
WARNING:nailgun.client:Received HTTP 404 response: {
  "error": {"message":"Resource common_parameter not found by id '42'"}
}
```
Same as for Organization:
```
In [8]: org = entities.Organization(server_config).create(create_missing=True)

In [9]: org.delete()
Out[9]: 
{u'cli_example': None,
 u'ended_at': u'2017-05-31 06:40:48 UTC',
 u'humanized': {u'action': u'Destroy',
  u'errors': [],
  u'input': [[u'organization',
    {u'link': u'/organizations/750/edit',
     u'text': u"organization 'WcXIJHQeOean'"}]],
  u'output': u''},
 u'id': u'65f4ea82-0809-4dc8-99b8-b9e576d81715',
 u'input': {u'organization': {u'id': 750,
   u'label': u'WcXIJHQeOean',
   u'name': u'WcXIJHQeOean'},
  u'remote_cp_user': u'admin',
  u'remote_user': u'admin'},
 u'label': u'Actions::Katello::Organization::Destroy',
 u'output': {},
 u'pending': False,
 u'progress': 1.0,
 u'result': u'success',
 u'started_at': u'2017-05-31 06:40:46 UTC',
 u'state': u'stopped',
 u'username': u'admin'}
```
Direct API request:
```
 λ curl -s -H "Accept:application/json" -k -u "admin:changeme" -X DELETE -d "{}" https://sat6.com/api/v2/common_parameters/43
{"id":43,"name":"𠝛杅ℽ𤬜왙鞇푳𨶣𡑮𨋢𠅰槫痺褞𡻖𤧫뾱𦌛ꟾ","value":"ﯣ𨾨𡒶䆘ᢠ𪉷橨屏㞛𨂎𤸳𦮺𦳩義𪴾𧱛Ί楾𣆁𩇍𓂏쓍","reference_id":null,"created_at":"2017-05-31T06:44:55.034Z","updated_at":"2017-05-31T06:44:55.034Z","priority":0,"hidden_value":"*****"}%   
```

**Comment by svtkachenko** [comment]
2. Regarding tests.
Using mixins allows to test separately only overridden methods and since there are no overrides, `InitTestCase` is enough (CommonParameter already added there).
Also I ran coverage locally and it shows that CommonParameter class fully covered.

**Comment by oshtaier** [comment]
Shouldn't we add test to `class UpdateTestCase(TestCase):` and `class CreateTestCase(TestCase):`?

**Comment by svtkachenko** [comment]
Theses testcases covers overridden methods only, basic methods covered in `test_entity_mixins.py`.
@coveralls agree with me that coverage has not changed :)

**Comment by oshtaier** [comment]
Who am I to argue with it =)

**Pull request merged**
