### PR TITLE
Add more attrs to ContentViewVersion

### PR DESCRIPTION
**Pull request by sean797**
This commit add repositories & description fields to ContentViewVersion.
It also fixes an issue with a CVV environment as it should have been LifecycleEnvironment

### CODE REVIEW

**Comment by sean797** [comment]
ping?

**Comment by sean797** [comment]
@akofink since CVV has no `environment` attribute (https://github.com/Katello/katello/blob/master/app/views/katello/api/v2/content_view_versions/base.json.rabl) this isn't a breaking change, it never work.

I think this is ready for merging..

**Comment by sghai** [comment]
@jyejare @evgeni  @ldjebran @oshtaier @abalakh @san7ket : guys, please review.

**Comment by evgeni** [comment]
The diff looks sane, but I have no time to test this, sorry.

**Comment by akofink** [comment]
Agreed, it doesn't appear to have been working at all before, so it seems safe to merge. Also, I *did* test this, and it works great. :1st_place_medal: We just need someone from @SatelliteQE with merge permissions.

**Comment by sean797** [comment]
I actually think with the time it seem to be taking for @SatelliteQE to review/merge some PRs driven by changes in `foreman-ansible-modules` it may be worth looking into giving some `foreman-ansible-modules` committers merge access here.

That was my intention with https://github.com/theforeman/foreman-ansible-modules/issues/185 anyway.

**Pull request merged**
