### PR TITLE
Add support for bulk available incremental updates

### PR DESCRIPTION
**Pull request by swadeley**
Hello

this is for new test, so test results will be at:
https://github.com/SatelliteQE/robottelo/pull/8024

### CODE REVIEW

**Review by mirekdlugosz — DISMISSED** [review]
LGTM

**Comment by mirekdlugosz** [comment]
@swadeley please fix travis failure. Complains about one line being tad too long.

**Comment by swadeley** [comment]
@mirekdlugosz fixed line that was too long.

Thank you

**Review by mirekdlugosz — DISMISSED** [review]

**Comment by mirekdlugosz** [comment]
@swadeley Github says there's a conflict between this PR and master. I believe it wasn't there last time I looked, must be caused by something we merged recently. Please rebase your PR.

**Comment by swadeley** [comment]
@mirekdlugosz rebased to fix that now, thank you

**Review by mirekdlugosz — APPROVED** [review]

**Review by jameerpathan111 — APPROVED** [review]
LGTM

**Review by pondrejk — APPROVED** [review]

**Comment by swadeley** [comment]
thank you!

**Pull request merged**
