### PR TITLE
Add Host disassociate operation

### PR DESCRIPTION
**Pull request by lhellebr**

### CODE REVIEW

**Comment by lhellebr** [comment]
I'm aware of missing test coverage, I will implement tests

**Comment by lhellebr** [comment]
Tests implemented, review pls

**Comment by ntkathole** [comment]
ok to test : tests/foreman/api/test_host.py -m tier1

**Comment by lhellebr** [comment]
> Looks good to me.
> @lhellebr can you submit new PR with cherry-pick to `stable-satellite`?

Of course, I was just waiting for this PR to be approved. Thanks!

**Comment by lhellebr** [comment]
Cherrypicked in https://github.com/SatelliteQE/nailgun/pull/687

**Pull request merged**
