### PR TITLE
Updated the missing fields for AuthSourceLDAP class for sat61.

### PR DESCRIPTION
**Pull request by kbidarkar**
*) Added a new section under docs for Jumpstart Nailgun.

### CODE REVIEW

**Comment by Ichimonji10** [comment]
Regarding the new fields: can you give some sort of proof that the new
attributes don't break existing functionality? ``AuthSourceLDAP(id=N).read()``
fails for me when working with one of our downstream systems. Is this an
upstream-only feature? Or something else?

```python
>>> attrs_list = [
...     entities.AuthSourceLDAP(id=id).read_json()
...     for id in ids  # iterable of 20 IDs
... ]
>>> l = list(attrs_list[0].keys())
>>> l.sort()
>>> l
[
    'account',
    'attr_firstname',
    'attr_lastname',
    'attr_login',
    'attr_mail',
    'attr_photo',
    'base_dn',
    'created_at',
    'external_usergroups',
    'host',
    'id',
    'ldap_filter',
    'name',
    'onthefly_register',
    'port',
    'tls',
    'type',
    'updated_at',
]
>>> for key in ('server_type', 'groups_base'):
...     [key in attrs for attrs in attrs_list]
...
[
    False,
    False,
    False,
    False,
    False,
    False,
    False,
    False,
    False,
    False,
    False,
    False,
    False,
    False,
    False,
    False,
    False,
    False,
    False,
    False,
]
[
    False,
    False,
    False,
    False,
    False,
    False,
    False,
    False,
    False,
    False,
    False,
    False,
    False,
    False,
    False,
    False,
    False,
    False,
    False,
    False,
]
```

**Comment by Ichimonji10** [comment]
Regarding the new documentation: NACK.

* The example makes use of `create_json`. The `create_json` method is fine and
  well to use *if* you have a good reason for using it instead of the
  higher-level `create` method. The documentation is targeted toward people who
  don't know how to use the library very well yet, so pointing people toward the
  lower-level `*_json` method is counterproductive.
* The very first code sample in the "Examples" page already does something
  similar: it shows how to create a `ServerConfig` object, how to use it to
  instantiate an entity object, and how to use an entity object.

IMO, the new bit of documentation expands the size of the documentation without
adding any substance to it.

**Comment by kbidarkar** [comment]
If you feel not needed, I will remove it, but if you imagine from the pov of a person who is new to nailgun, he would have to go through a lot of documentation to get started. I thought this would help over there. Regarding just create, will update.

**Comment by Ichimonji10** [comment]
Thank you for removing that. I may file a PR to trim down the documentation a little bit and make things more streamlined for a new user. You've given me some ideas.

**Comment by Ichimonji10** [comment]
Regarding the new fields: can you give some sort of proof that the new
attributes don't break existing functionality? `AuthSourceLDAP(id=N).read()`
fails for me when working with one of our downstream systems.

**Comment by Ichimonji10** [comment]
From IRC:

    <ichimonji10> kbidarka: The server doesn't return the groups_base or server_type attributes when you read an AuthSourceLDAP. But it does return those fields when you create or update an AuthSourceLDAP. That right there is a bug - I (or you, if you feel like it) can file a BZ for that.
    <ichimonji10> kbidarka: The work-around is a clever bit of hackery: whenever the user calls read(), under the hood we call update() and don't actually pass any values to the server.
    <ichimonji10> If you just leave your PR up, I'll put together a second commit that you can cherry-pick. I won't make you dive this deep in to NailGun. :)

**Comment by Ichimonji10** [comment]
@kbidarkar You can go ahead and cherry-pick the second commit from here: https://github.com/SatelliteQE/nailgun/compare/master...Ichimonji10:fix-authsource

You can do something like this:

    git remote add ichi https://github.com/Ichimonji10/nailgun.git
    git fetch ichi
    git cherry-pick e78f2e48583d6764b2c656359c7ff925c167893b

Or, if you like, I'll just submit that branch as a pull request. Whatever works best for you.

**Comment by Ichimonji10** [comment]
ACK pending cherry-pick

**Comment by Ichimonji10** [comment]
ACK

**Comment by JacobCallahan** [comment]
ACK

**Comment by elyezer** [comment]
:+1:

**Pull request merged**
