### PR TITLE
Added Discovery Rule entity

### PR DESCRIPTION
**Pull request by sghai**

### CODE REVIEW

**Comment by Ichimonji10** [comment]
Very nicely done. ACK.

**Comment by oshtaier** [comment]
If that is possible it will be very nice if you can show few examples for Discovery Rule entity creation or update procedures
ACK

**Comment by sghai** [comment]
@oshtaier : Sure, Plan is add tests in robottelo around Discovery Rules. But here is an example to create rule. 

```
In [5]: hg = entities.HostGroup(server_config, name='test12').create()
In [8]: entities.DiscoveryRule(server_config, name='rule2', search='cpu_count = 1', hostgroup=hg.id).create_json()

Out[8]: 
{u'created_at': u'2015-08-19T07:41:25Z',
 u'enabled': True,
 u'hostgroup_id': 6,
 u'hostname': u'',
 u'id': 3,
 u'max_count': 0,
 u'name': u'rule2',
 u'priority': 0,
 u'search': u'cpu_count = 1',
 u'updated_at': u'2015-08-19T07:41:25Z'}
```

**Comment by sghai** [comment]
Also made a small change. I realized that hostgroup should be OneToOne Field. Thanks @oshtaier :)

**Comment by Ichimonji10** [comment]
Looks great. I added the `EntitySearchMixin` to the `HostGroup` and
`DiscoveryRule` entities and played around, and everything worked well.

```python
>>> host_groups = entities.HostGroup().search()
>>> len(host_groups)
4
>>> host_groups[0].id
2
>>> len(entities.DiscoveryRule().search())
0
>>> discovery_rule = entities.DiscoveryRule(
...     name='test_name',
...     rch='cpu_count = 1',
...     hostgroup=host_groups[0],
... ).create()
>>> len(entities.DiscoveryRule().search())
1
>>> discovery_rule.get_values().keys()
dict_keys(['name', 'priority', 'id', 'enabled', 'search', 'hostgroup', 'hostname'])
>>> discovery_rule.id
1
>>> discovery_rule.enabled
True
>>> discovery_rule.search
'cpu_count = 1'
>>> discovery_rule.hostname
''
>>> discovery_rule.hostgroup.id
2
```

**Pull request merged**
