### PR TITLE
search subs

### PR DESCRIPTION
**Pull request by sean797**
from https://github.com/SatelliteQE/nailgun/pull/466

ping @renzon

### CODE REVIEW

**Comment by renzon** [comment]
Can you add a test case for it and also a example of working console section? You've provided only a failure on #466 and would be nice to check it's working. 

Since _get_entity_ids is used by all entities I would say changing it can have a very wide impact. If test I could check if there is a way to change the read method, maybe overriding it, so this change would affect only Subscription itself.

**Comment by renzon** [comment]
I have created an issue for this, check #475

**Comment by renzon** [comment]
Hey @sean797, I came up with a less intrusive workaroung. Instead of changing a function which is used for all entities, I've just overridden read method on Subscription. Take a look on #476

**Comment by rochacbruno** [comment]
@renzon @sean797 as #476 is merged can we close this one?

**Comment by sean797** [comment]
Yes, sorry i've been inactive the last couple of weeks. Thnkas @renzon & @rochacbruno 👍

**Pull request closed without merging**
