### PR TITLE
Add support for missing Puppet environment entity

### PR DESCRIPTION
**Pull request by swadeley**
##### Description of changes
Hello

Nailgun failed to create an org in Satellite 7 snap 2

`E           nailgun.entity_mixins.MissingValueError: Cannot find a value for the "environment" field.`

I presume due to removal of default Puppet environment support.

##### Upstream API documentation, plugin, or feature links

On 6.10.1 and Sat7.0

http://<satellite_server>/apidoc/v2/organizations/create.html
organization[environment_ids]optional , nil allowed

##### Functional demonstration

Provide an execution of the modified code, with ipython code blocks or screen shots.
You can exercise the code as raw API calls or using any other method.

```
pytest tests/foreman/api/test_organization.py -k test_positive_create_with_name_and_description
=================================== test session starts ==========================
platform linux -- Python 3.9.9, pytest-6.2.5, py-1.10.0, pluggy-0.13.1
shared_function enabled - OFF - scope:  - storage: file
rootdir: /home/sjw/sat6/robottelo, configfile: pyproject.toml
plugins: mock-3.6.1, ibutsu-1.16, forked-1.3.0, services-2.2.1, cov-3.0.0, reportportal-5.0.8, xdist-2.4.0
collected 43 items / 36 deselected / 7 selected                                                                                                                                                   

tests/foreman/api/test_organization.py .......  

============== 7 passed, 36 deselected, 15 warnings in 55.27s =======================
```

Your contribution should include updates to the unit tests, covering the modified portions or adding new coverage.

Example:
```
# Demonstrate functional Snapshot read in ipython
In [1]: from nailgun.entities import Snapshot
In [2]: Snapshot(host='sat.instance.addr.com', id='snap_uuid').read()
Out [2]: <read method result>
```

##### Additional Information

Any additional notes for reviewers, comments about the change, TODO lists on WIP PRs, etc.

### CODE REVIEW

**Comment by vsedmik** [comment]
I wonder how would this change impact the org creation on the puppet-enabled Satellite. I need to check...

**Review by rplevka — COMMENTED** [review]
@swadeley - could we perhaps introduce a new (dynaconf) setting that would reflect the puppet enabled state on the current satellite and append this `environment` entity based on its value?
we can set the setting via env vars from the pipeline

**Comment by jyejare** [comment]
@rplevka Nailgun doesn't supports the dynaConf yet, so dynamic setting wont work here :(

**Comment by swadeley** [comment]
Now with @JacobCallahan improvements:

robottelo]$ pytest tests/foreman/api/test_organization.py -k test_positive_create_with_name_and_description
=================================== test session starts ====================================
platform linux -- Python 3.9.9, pytest-6.2.5, py-1.10.0, pluggy-0.13.1
shared_function enabled - OFF - scope:  - storage: file
rootdir: /sat6/robottelo_1/robottelo, configfile: pyproject.toml
plugins: mock-3.6.1, ibutsu-1.16, forked-1.3.0, services-2.2.1, cov-3.0.0, reportportal-5.0.8, xdist-2.4.0, repeat-0.9.1
collected 43 items / 36 deselected / 7 selected                                                                                                                                                   

tests/foreman/api/test_organization.py .......

============= 7 passed, 36 deselected, 15 warnings in 53.05s ======================

**Comment by swadeley** [comment]
> I wonder how would this change impact the org creation on the puppet-enabled Satellite. I need to check...

With improvements suggest by @JacobCallahan this change should now be safe for your test case.

**Comment by JacobCallahan** [comment]
@swadeley looks like you've got to run pre-commit

**Comment by swadeley** [comment]
> @swadeley looks like you've got to run pre-commit

should be fixed now

thank you

**Comment by jameerpathan111** [comment]
@swadeley I tested this code and I am getting `*** nailgun.entity_mixins.BadValueError: An inappropriate value was assigned to the "compute_resource" field. An iterable of entities and/or entity IDs should be assigned, but the following was given: None` error because of this new change.
for ex. while trying to search location: `entities.Location().search(query={'search': f'name="Default Location"'})[0]`

**Comment by JacobCallahan** [comment]
@jameerpathan111 thanks for testing this out! Can you also add the full traceback? That would be helpful

**Comment by jameerpathan111** [comment]
@JacobCallahan @swadeley 
```================================================================================= FAILURES =================================================================================
_________________________________________________________________________________ test_org _________________________________________________________________________________

    @pytest.mark.run_in_one_thread
    @pytest.mark.tier3
    def test_org():
        """ ds"""
>       loc = entities.Location().search(query={'search': f'name="Default Location"'})[0]

tests/foreman/api/test_rhcloud.py:52: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../nailgun/nailgun/entity_mixins.py:1357: in search
    entity = type(self)(self._server_config, **result)
../nailgun/nailgun/entities.py:4775: in __init__
    super().__init__(server_config, **kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = nailgun.entities.Location()
server_config = nailgun.config.ServerConfig(url='https://satellite.example.com:443', auth=('admin', 'changeme'), verify=False)
kwargs = {'compute_resource': None, 'description': None, 'domain': None, 'environment': None, ...}, field_name = 'compute_resource', field_value = None
field = <nailgun.entity_fields.OneToManyField object at 0x7f444ea5fe80>

    def __init__(self, server_config=None, **kwargs):
        if server_config is None:
            server_config = _get_server_config()
        self._server_config = server_config
    
        # Subclasses usually define a set of fields and metadata before calling
        # `super`, but that's not always the case.
        if not hasattr(self, '_fields'):
            self._fields = {}
        if not hasattr(self, '_meta'):
            self._meta = {}
        if 'read_type' not in self._meta or self._meta['read_type'] != 'base':
            self._fields.setdefault('id', IntegerField(unique=True))
    
        # Check that a valid set of field values has been passed in.
        if not set(kwargs.keys()).issubset(self._fields.keys()):
            raise NoSuchFieldError(
                f'Valid fields are {list(self._fields.keys())}, invalid field(s) passed '
                f'to entity: {set(kwargs.keys()).difference(set(self._fields.keys()))}'
            )
    
        # Iterate through the values passed in and assign them as instance
        # variable to `self`. Make sure to transform entity IDs into entity
        # objects. (This feature is described in the docstring.)
        for field_name, field_value in kwargs.items():  # e.g. ('admin', True)
            field = self._fields[field_name]  # e.g. A BooleanField object
            if isinstance(field, OneToOneField):
                if field_value is None:
                    setattr(self, field_name, field_value)
                else:
                    setattr(
                        self,
                        field_name,
                        _make_entity_from_id(field.gen_value(), field_value, self._server_config),
                    )
            elif isinstance(field, OneToManyField):
                # `try:; …; except TypeError:; raise BadValueError(…)` better
                # follows the "ask forgiveness" principle. However, a TypeError
                # could be raised for any number of reasons. For example,
                # `field_value` could have a faulty __iter__ implementation.
                if not isinstance(field_value, Iterable):
>                   raise BadValueError(
                        f'An inappropriate value was assigned to the "{field_name}" '
                        'field. An iterable of entities and/or entity IDs '
                        f'should be assigned, but the following was given: {field_value}'
                    )
E                   nailgun.entity_mixins.BadValueError: An inappropriate value was assigned to the "compute_resource" field. An iterable of entities and/or entity IDs should be assigned, but the following was given: None

../nailgun/nailgun/entity_mixins.py:422: BadValueError
```
If I had to guess, I would say it's failing because of https://github.com/SatelliteQE/nailgun/pull/799/files#diff-d5a75c8cb33106e7c67337537a83fb7f67da1de758a85f45e1e260d1e3250ac5R259 (`return None`).

**Comment by JacobCallahan** [comment]
This likely could be mitigated by adding a check to the line above the raise.

Something like `if field_value and is instance(...`

**Comment by jyejare** [comment]
@JacobCallahan @swadeley @jameerpathan111 Do u really think this PR is needed **now**?

Why?
1. Cause we have already branched 6.10 apart :)
2. Just simply removing the environment parameter should be good enough for 7.0(master) instead of the modifications we introduced to keep the param for 6.10 and 7.0
3. We need not to cherry-pick the removal in 6.10.z branch or any modifications are required for 6.10 as the environment already exists for 6.10

@swadeley You should now be good with the initial version of your PR :)

**Comment by jameerpathan111** [comment]
> @JacobCallahan @swadeley @jameerpathan111 Do u really think this PR is needed **now**?

yes

>     2. Just simply removing the environment parameter should be good enough for 7.0(master) instead of the modifications we introduced to keep the param for 6.10 and 7.0

Even if Puppet feature is disabled by default we still support it with Satellite 7.0 that means we still need to test it.
That's why we will need this change.

**Comment by jyejare** [comment]
@jameerpathan111 Ok for compatibility with depreciated components we can keep it! But right now the whole automation is on stake with this issue ! 

So we should either put this on number one prio for SatQE or just merge it with the removed environment parameter(that will reduce the fail count to 150 from 1200 fails) and later open a PR for puppet support (that might fix 10-15 tests)!

Its already 4 snaps and we dont have automation results in hand, we dont want to see the failures count until the last snaps that we have seen in 6.10 again :(

**Comment by JacobCallahan** [comment]
@jyejare I trust your decision here. We can address this version of the fix after shutdown.

Please open a pr with the feature removal and tag me. Let's get this in today 🙂

**Comment by jyejare** [comment]
Thanks for the trust @JacobCallahan ! I opened counter PR https://github.com/SatelliteQE/nailgun/pull/804 ! Please review !

**Comment by swadeley** [comment]
> This likely could be mitigated by adding a check to the line above the raise.
> 
> Something like `if field_value and is instance(...`

Hello @JacobCallahan 

I  rebased and made this change:

```
-                if not isinstance(field_value, Iterable):
+                if field_value and not isinstance(field_value, Iterable):
```

but it still fails

   `ERROR: test_host_with_image (tests.test_entities.SearchTestCase)
   Call :meth:`nailgun.entities.Host.search` for a host with image
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/nailgun/nailgun/nailgun/entities.py", line 4438, in search
    entity = type(self)(self._server_config, **result)
  File "/home/runner/work/nailgun/nailgun/nailgun/entities.py", line 3682, in __init__
    super().__init__(server_config, **kwargs)
  File "/home/runner/work/nailgun/nailgun/nailgun/entity_mixins.py", line 430, in __init__
    _make_entities_from_ids(field.gen_value(), field_value, self._server_config),
  File "/home/runner/work/nailgun/nailgun/nailgun/entity_mixins.py", line 155, in _make_entities_from_ids
    for entity_or_id in entity_objs_and_ids
  TypeError: 'NoneType' object is not iterable`


This PR seems good https://github.com/SatelliteQE/nailgun/pull/805

**Pull request closed without merging**
