### PR TITLE
Adding parent_name to Location entity

### PR DESCRIPTION
**Pull request by ncelebic**
Helps when automating tasks that need information about nested Locations.

### CODE REVIEW

**Comment by oshtaier** [comment]
Probably you meant:
`'parent': entity_fields.OneToOneField(Location),`

**Comment by ncelebic** [comment]
@svtkachenko Getting the parent as an entity is useful, but if you're 4 deep, you have to do an ugly loop to assemble the full name that is available right in text from the api.

**Comment by svtkachenko** [comment]
@ncelebic You mean that additional read?
```
In [5]: l1 = entities.Location(server_config).create(create_missing=True)

In [6]: l2 = entities.Location(server_config, parent=l1).create(create_missing=True)

In [11]: l2.parent.read().name
Out[11]: u'OCuwHvmpFhrs'
```

Adding raw fields if they can be expressed via nailgun's entity contradicts nailgun's design ._.

**Comment by ncelebic** [comment]
@svtkachenko <https://github.com/svtkachenko> How I got it working was this:

host["location_id"] = 6
location = Location(id=host['location_id']).read()
parentid = location.parent.id
locid = location.id
while locid != 1:
  parentloc = Location(id=parentid).read()
  try:
    parentid = parentloc.parent.id
  except:
    pass
  locid = parentloc.id
  host['location_fullname'] = parentloc.name + "/" +
host['location_fullname']

I'd end up with 1/2/3/4/5/6 after iterating.

My terrible code aside, it's the best way I could think to deal with this.
I need to assemble the entire location name.

**Comment by ncelebic** [comment]
I've changed the parent_name to the parent entity as requested.  My environment is probably not that standard, and I can live with a terrible loop.

**Comment by ncelebic** [comment]
No problem at all.
```
>>> from nailgun.config import ServerConfig
>>> from nailgun.entities import Location
>>> from pprint import pprint
>>> location=Location(id=19).read()
>>> pprint(location)
```
nailgun.entities.Location(nailgun.config.ServerConfig(url=u'https://satellite', auth=(u'nailauth', u'passwd')), smart_proxy=[], domain=[], description=u'', parent=nailgun.entities.Location(nailgun.config.ServerConfig(url=u'https://satellite', auth=(u'nailauth', u'passwd')), id=15), user=[nailgun.entities.User(nailgun.config.ServerConfig(url=u'https://satellite', auth=(u'nailauth', u'passwd')), id=8)], id=19, subnet=[], name=u'City1', provisioning_template=[], hostgroup=[], environment=[], config_template=[], compute_resource=[], media=[], organization=[])

**Comment by svtkachenko** [comment]
@ncelebic You can use `read_json` and get any raw value directly from json dict.

**Comment by svtkachenko** [comment]
@ncelebic 
```
In [5]: l1 = entities.Location(server_config).create(create_missing=True)

In [6]: l2 = entities.Location(server_config, parent=l1).create(create_missing=True)

In [7]: l3 = entities.Location(server_config, parent=l2).create(create_missing=True)

In [10]: l3.read_json()['parent_name']
Out[10]: u'GCszeRydMfa/EGClbz'
```

**Pull request merged**
