### PR TITLE
adding default_content_view and library fields to Organization entity

### PR DESCRIPTION
**Pull request by anarang**

### CODE REVIEW

**Comment by sthirugn** [comment]
ACK

**Comment by Ichimonji10** [comment]
Don't merge this *quite* yet.

**Comment by Ichimonji10** [comment]
This works well on current versions of Satellite

    >>> org = entities.Organization(id=1).read()
    >>> org.default_content_view.id, org.library.id
    (1, 1)
    >>> org.default_content_view.read().name, org.library.read().name
    ('Default Organization View', 'Library')

Older versions of satellite do not have a "default_content_view" or "library" field on the "Organization" entity. I tested these changes against Satellite 6.0.8, and here's the exception raised:

> nailgun.entity_mixins.MissingValueError: Cannot find a value for the "default_content_view" field. Searched for keys named ('default_content_view', 'default_content_view_id'), but available keys are dict_keys(['subnets', 'updated_at', 'created_at', 'title', 'users', 'hostgroups', 'owner_details', 'service_level', 'redhat_repository_url', 'locations', 'select_all_types', 'domains', 'smart_proxies', 'media', 'environments', 'id', 'service_levels', 'compute_resources', 'description', 'default_info', 'label', 'parameters', 'config_templates', 'name']).

Please make a change a bit more like this:

    >>> org = entities.Organization(id=1).read()
    >>> 'default_content_view' in org.get_fields(), 'library' in org.get_fields()
    (False, False)

Here's a diff to accomplish this change while retaining backward compatibility:


```diff
diff --git a/nailgun/entities.py b/nailgun/entities.py
index 0deeda7..3f0c847 100644
--- a/nailgun/entities.py
+++ b/nailgun/entities.py
@@ -33,7 +33,7 @@ from nailgun.entity_mixins import (
     EntityUpdateMixin,
     _poll_task,
 )
-from packaging.version import parse
+from packaging.version import parse, Version
 from time import sleep
 import random
 
@@ -2254,13 +2254,11 @@ class Organization(
                 AbstractComputeResource
             ),
             'config_template': entity_fields.OneToManyField(ConfigTemplate),
-            'default_content_view': entity_fields.OneToOneField(ContentView),
             'description': entity_fields.StringField(),
             'domain': entity_fields.OneToManyField(Domain),
             'environment': entity_fields.OneToManyField(Environment),
             'hostgroup': entity_fields.OneToManyField(HostGroup),
             'label': entity_fields.StringField(str_type='alpha'),
-            'library': entity_fields.OneToOneField(LifecycleEnvironment),
             'media': entity_fields.OneToManyField(Media),
             'name': entity_fields.StringField(required=True),
             'realm': entity_fields.OneToManyField(Realm),
@@ -2269,6 +2267,14 @@ class Organization(
             'title': entity_fields.StringField(),
             'user': entity_fields.OneToManyField(User),
         }
+        version = getattr(server_config, 'version', Version('1!0'))
+        if version >= Version('6.1.1'):  # default: True
+            self._fields.update({
+                'default_content_view': entity_fields.OneToOneField(
+                    ContentView
+                ),
+                'library': entity_fields.OneToOneField(LifecycleEnvironment),
+            })
         self._meta = {
             'api_path': 'katello/api/v2/organizations',
             'server_modes': ('sat', 'sam'),
```

**Comment by Ichimonji10** [comment]
ACK pending comments

**Comment by Ichimonji10** [comment]
Manually rebased and merged. Thank you @anarang.

**Comment by Ichimonji10** [comment]
FYI, I'd definitely recommend spending some time with some learning resources. There's plenty of great free resources:

* git: [try.github.io](https://try.github.io/levels/1/challenges/1), [git-scm.com](http://git-scm.com/doc), [@omaciel gist](https://gist.github.com/omaciel/7811339)
* nailgun: [nailgun.readthedocs.org](http://nailgun.readthedocs.org/en/latest/)
* python: [official documentation (python 2)](https://docs.python.org/3/tutorial/index.html), [official documentation (python 3)](https://docs.python.org/2.7/tutorial/index.html)

**Comment by anarang** [comment]
@Ichimonji10 Thanks, I'll look at those. I have to say that please do not merge the PR manually, but via the UI. It may be the best practice to merge that way but I would like to track my contributions through the graph [here](https://github.com/SatelliteQE/robottelo/graphs/contributors). As of now, both the PRs have been merged manually and my contributions are not visible on the graph neither I am listed as a contributor yet(because the PRs got closed and not merged according to github). Please take this into consideration for the next PR. Thanks :)

**Comment by Ichimonji10** [comment]
> I would like to track my contributions through the graph here.

Understood, and understandable.

> please do not merge the PR manually

Please take some time working through the git-related resources I have linked to. I will gladly merge your PRs via the UI if they are well formed. (one commit per logical change, up-to-date, good commit messages, etc) It is important to me that the commit history is readable and that changes can be reverted.

**Comment by elyezer** [comment]
Yeah, having good commit history is definitely a must. We all have to be aware of the comments and try to rebase as much as possible in order to ensure the good history.

**Comment by anarang** [comment]
@elyezer @Ichimonji10 agreed and thanks :)

**Pull request closed without merging**
