### PR TITLE
Adding new 'registry' entity

### PR DESCRIPTION
**Pull request by oshtaier**
After recent fix for https://bugzilla.redhat.com/show_bug.cgi?id=1206679 defect, it become possible to add one more entity to API

### CODE REVIEW

**Comment by elyezer** [comment]
Does this entity works? An sample run would be good.

ACK

**Comment by Ichimonji10** [comment]
I think #2716 shows that this works. My only concern is the `read()` method. Does it work correctly? I'm wondering because of the presence of the `password` attribute. Satellite doesn't usually return sensitive info like that.

**Comment by oshtaier** [comment]
I actually have PR pending in Robottelo right now that have a lot of tests proving that entity works properly

**Comment by oshtaier** [comment]
Yes, it is returning password :) I verified that fact explicitly

**Comment by Ichimonji10** [comment]
Aha! You're ahead of me. Thank you. ACK

**Pull request merged**
