### PR TITLE
Add possibility to query deb packages for host

### PR DESCRIPTION
**Pull request by dosas**
##### Description of changes

Add possibility to query deb packages for host

##### Upstream API documentation, plugin, or feature links

There is no up to date foreman documentation online but the api is listed [here](https://github.com/Katello/katello/blob/master/engines/bastion_katello/app/assets/javascripts/bastion_katello/hosts/host-debs.factory.js)

##### Functional demonstration

```
ipdb> host.debs({"per_page": 20})
{'total': 385, 'subtotal': 385, 'selectable': 385, 'page': 1, 'per_page': 20, 'error': None, 'search': None, 'sort': {'by': 'name', 'order': 'asc'}, 'results':  ...
```

##### Additional Information
possible PRT test `tests/foreman/api/test_errata.py`

### CODE REVIEW

**Comment by omkarkhatavkar** [comment]
Can one of the admins verify this patch?

**Comment by ColeHiggins2** [comment]
Looks fine to me. Just adding a new entity and updating path, will not affect current automation

**Review by ColeHiggins2 — APPROVED** [review]

**Review by vijaysawant — APPROVED** [review]

**Comment by dosas** [comment]
@ColeHiggins2  @vijaysawant I do not have merge rights, could one of you merge this?

**Comment by dosas** [comment]
@vijaysawant Thank you. Could you also take care of the cherry-pick PRs?

**Pull request merged**
