### PR TITLE
Increase timeout for manifest upload

### LINKED ISSUE #293: Fix upload manifest to account for slowness when number of org increases.
Reference: https://github.com/SatelliteQE/robottelo/pull/3483

### PR DESCRIPTION
**Pull request by abalakh**
As per [this discussion](https://github.com/SatelliteQE/robottelo/pull/3483#issuecomment-221566076) and [BZ1339696](https://bugzilla.redhat.com/show_bug.cgi?id=1339696), manifest upload duration increases depending on number of organizations and activation keys present in system. And in the end of automation run, according to @rplevka's investigation, it takes up to 11 minutes to upload a manifest.
Updating timeout for manifest upload operation to 15 mins so we can successfully receive the results.
Closes #293

### CODE REVIEW

**Comment by oshtaier** [comment]
Seems good as for me
@elyezer @Ichimonji10 Could you please, check this one out?

**Comment by abalakh** [comment]
Can't test the change ATM as CI is still running the tests (and, basically, our CI boxes are the only place where we can validate the change). Will run some random manifest upload test as soon as existing auto jobs finish execution.

**Comment by sthirugn** [comment]
ACK pending test results

**Comment by abalakh** [comment]
As CI boxes are busy again (now with 8threaded tasks), i used my custom boxes with all the robottelo tests executed (from SatelliteQE/robottelo#3490). I've picked up random `api.test_contentview.ContentViewRedHatContent.test_positive_add_rh` which is failing for a long time with importing manifest timeout and executed it.

Test result:
```python
/home/andrii/env/bin/python /home/andrii/workspace/pycharm-2016.1.3/helpers/pydev/pydevd.py --multiproc --qt-support --client 127.0.0.1 --port 40489 --file /home/andrii/workspace/pycharm-2016.1.3/helpers/pycharm/pytestrunner.py -p pytest_teamcity /home/andrii/workspace/robottelo/tests/foreman/api/test_contentview.py "-k ContentViewRedHatContent and test_positive_add_rh"
Testing started at 1:10 PM ...
Connected to pydev debugger (build 145.971)
warning: Debugger speedups using cython not found. Run '"/home/andrii/env/bin/python" "/home/andrii/workspace/pycharm-2016.1.3/helpers/pydev/setup_cython.py" build_ext --inplace' to build.
pydev debugger: process 48606 is connecting

============================= test session starts ==============================
platform linux2 -- Python 2.7.10, pytest-2.9.1, py-1.4.31, pluggy-0.3.1
rootdir: /home/andrii/workspace/robottelo, inifile: 
plugins: xdist-1.13.1, repeat-0.2
collected 51 items

workspace/robottelo/tests/foreman/api/test_contentview.py ..

 49 tests deselected by '-k ContentViewRedHatContent and test_positive_add_rh' =
================== 2 passed, 49 deselected in 452.23 seconds ===================

Process finished with exit code 0
```

For the record, there was following debug message:
```
2016-05-27 13:17:40 - nailgun.client - DEBUG - Received HTTP 200 response: {"id":"3cb11532-de0f-4f02-b530-1b167ece4964","label":"Actions::Katello::Provider::ManifestImport","pending":false,"username":"admin","started_at":"2016-05-27 10:10:45 UTC","ended_at":"2016-05-27 10:17:35 UTC","state":"stopped","result":"success","progress":1.0,"input":{"provider":{"id":1314,"name":"Red Hat"},"organization":{"id":882,"name":"fryKuIjl","label":"fryKuIjl"},"path":"/usr/share/foreman/tmp/import_a05ad82ddc836882b132.zip","force":null,"remote_user":"admin","remote_cp_user":"admin","locale":"en"},"output":{},"humanized":{"action":"Import Manifest","input":[["organization",{"text":"organization 'fryKuIjl'","link":"/organizations/882/edit"}]],"output":"","errors":[]},"cli_example":null}
```
So manifest import took 6 minutes 50 seconds to finish. That proves this change works as expected.

**Pull request merged**
