### PR TITLE
[WIP] Fix *_payload methods to process entity ids, not just entities

### PR DESCRIPTION
**Pull request by abalakh**

### CODE REVIEW

**Comment by ntkathole** [comment]
[test]

**Comment by ntkathole** [comment]
ok to test : tests/foreman/api/test_user.py

**Comment by ntkathole** [comment]
ok to test : tests/foreman/api/test_user.py

**Comment by ntkathole** [comment]
ok to test

**Comment by ntkathole** [comment]
ok to test

**Comment by ntkathole** [comment]
ok to test : tests/foreman/api/test_activationkey.py -k test_positive_update_name

**Comment by mirzal** [comment]
@abalakh What is status of this? Are you still working on it? If not, what is missing and needs to be done if anyone would like to pick it up?

I see it labeled as bug and 6.5. What bug does it address? Should we merge it before branching 6.5, or cherry-pick if we merge it after branch?

Robottelo already has 6.5.z branch and it makes sense to branch 6.5.z here before we start receiving PRs for new features in 6.6.

**Comment by abalakh** [comment]
@mirzal sorry, didn't have time for this PR and now i don't have env, maybe it will be faster if smbd picks it up.
If i remember correctly, easy reproducer was the following:
```python
subnet = entities.Subnet().create()
subnet.tftp = 1
subnet = subnet.update(['tftp'])
```
As you can see in code section, previous logic was always looking for `.id` attribute meaning it was working only with enitities and wasn't supporting direct ids (althought according to docs it should).
The fix itself should be good and working ok, but as it's core change - it requires some good testing for at least few entities. I've provided 1 example for `update_payload()` for `OneToOne` field, but `create_payload()` and `OneToMany` field should be checked as well. Unit tests would be great addition as well.

It's labeled with `bug` as according to docs we support raw ids altogether with entities instances when creating or updating some other entity, but in fact it wasn't always working -> bug.

Imo it shouldn't block branching, this bug was there for a long time (most likely from project start) and uncovered only in 6.5, so it's not so critical and can be cherry-picked later.

**Comment by san7ket** [comment]
ok to test : tests/foreman/api/ m "tier2 and not run_in_one_thread and not stubbed"

**Comment by san7ket** [comment]
ok to test : tests/foreman/api/ -m "tier2 and not run_in_one_thread and not stubbed"

**Comment by san7ket** [comment]
ok to test : tests/foreman/api/ -m "tier2 and not run_in_one_thread and not stubbed"

**Comment by san7ket** [comment]
ok to test : test_{a..h}*.py -m tier2 -n 4

**Comment by mirzal** [comment]
Just for the record, we branched 6.5.z today and this change didn't make it in. As it stands, it will be merged into master. We can cherry-pick it into 6.5.z latwer.
[abalakh comment](https://github.com/SatelliteQE/nailgun/pull/611#issuecomment-490089473) contains good summary of work that needs to be done.

**Comment by san7ket** [comment]
Pending work on this PR,

- [ ] Find a volunteer to assign this to

- [ ]  This should have unit tests around changes eg:  update_payload() for OneToOne field, and create_payload() and OneToMany 

- [ ] Run some chunk of robottelo tests against this branch. API Tests marked with upgrade marker coul d be great candidate to do a sanity check around changes

**Comment by ntkathole** [comment]
Can one of the admins verify this patch?

**Comment by JacobCallahan** [comment]
@SatelliteQE/tier-1-reviewers @SatelliteQE/tier-2-reviewers let's discuss what we want to do with this soon.

**Comment by jyejare** [comment]
Closing and reopening the same PR for running checks!

**Pull request closed without merging**
