### PR TITLE
Fix #4, #46

### LINKED ISSUE #4: Do not populate required fields with random values
By default, calls to method `EntityCreateMixin.create` and several of its siblings causes all required and empty fields to be given random values.

As an example of this, let's say that you do the following:

```python
from nailgun import entities
entities.Repository(name='foo').create()
```

If you do this, then the "content_type", "url" and "product" fields are filled in, as all three of them are marked as required. The "product" field is a foreign key field, so the above code creates a tree of bogus entities. This is great for API testing, but not so much for other users.

Closing this bug requires that the following be done:

* Turn off automatic attribute creation by default.
* Provide some mechanism for enabling automatic attribute creation if so desired by a user.

### PR DESCRIPTION
**Pull request by Ichimonji10**
These two changes are logically separate, but I'm bundling them together for the sake of expediency. I have a matching pull request ready to go on Robottelo, and if this is merged, then I can release 0.12.0 and unblock that PR.

For full details on the changes in this PR, please see the individual commit messages. Summary of changes:

* Do not automatically create missing values on entities. The default assumption among users (especially new users) is likely that if a value is missing, then it will not be created, and this change makes NailGun more accessible to a wide audience by catering to that assumption.
* Refactor out some common response handling code. This makes the existing code base slightly smaller, common response handling code makes silly mistakes harder to commit, and this makes it easier for interested individuals to contribute (the existing code looks more uniform and is therefore easier to study and replicate).

### CODE REVIEW

**Comment by omaciel** [comment]
ACK

**Comment by sthirugn** [comment]
squash commits?

**Comment by sthirugn** [comment]
ACK

**Comment by elyezer** [comment]
:+1:

**Pull request merged**
