### PR TITLE
Test version-related logic to unit test suite

### PR DESCRIPTION
**Pull request by Ichimonji10**
Certain entities have different fields based on which software version the
server is running. Add unit tests for this type of logic.

Also, drop outdated pylint directives. Pylint apparently now knows to not
complain about the naming of unittest's `setUp` and `setUpClass` methods.

### CODE REVIEW

**Comment by elyezer** [comment]
ACK

**Comment by Ichimonji10** [comment]
Rebased.

**Comment by omaciel** [comment]
ACK.  If rebased again feel free to merge.

**Comment by Ichimonji10** [comment]
Rebased again.

**Comment by elyezer** [comment]
APT

**Pull request merged**
