### PR TITLE
Update `Domain` to include a `SmartProxy` field.

### PR DESCRIPTION
**Pull request by omaciel**
Since a `entities.Domain` can be associated to a `entities.SmartProxy`
by its `id`, I have updated the class to accept a new field (integer).

Preliminary testing shows:

```python
In [10]: org = Organization(id=1).read()

In [12]: loc = Location(id=2).read()

In [13]: capsule = SmartProxy(id=1).read()

In [15]: foo = Domain(organization=[org], location=[loc], dns_id=capsule.id).create()

In [16]: foo
Out[16]: nailgun.entities.Domain(nailgun.config.ServerConfig(url=u'https://ibm-x3250m4-06.lab.eng.rdu2.redhat.com', verify=False, version=<Version('6.1')>, auth=(u'admin', u'fromgod1')), domain_parameters_attributes=[], location=[nailgun.entities.Location(nailgun.config.ServerConfig(url=u'https://ibm-x3250m4-06.lab.eng.rdu2.redhat.com', verify=False, version=<Version('6.1')>, auth=(u'admin', u'fromgod1')), id=2)], dns_id=1, organization=[nailgun.entities.Organization(nailgun.config.ServerConfig(url=u'https://ibm-x3250m4-06.lab.eng.rdu2.redhat.com', verify=False, version=<Version('6.1')>, auth=(u'admin', u'fromgod1')), id=1)], fullname=None, id=4, name=u'shg36dpgdz')

In [18]: Domain(id=4).read()

Out[18]: nailgun.entities.Domain(nailgun.config.ServerConfig(url=u'https://ibm-x3250m4-06.lab.eng.rdu2.redhat.com', verify=False, version=<Version('6.1')>, auth=(u'admin', u'fromgod1')), domain_parameters_attributes=[], location=[nailgun.entities.Location(nailgun.config.ServerConfig(url=u'https://ibm-x3250m4-06.lab.eng.rdu2.redhat.com', verify=False, version=<Version('6.1')>, auth=(u'admin', u'fromgod1')), id=2)], dns_id=1, organization=[nailgun.entities.Organization(nailgun.config.ServerConfig(url=u'https://ibm-x3250m4-06.lab.eng.rdu2.redhat.com', verify=False, version=<Version('6.1')>, auth=(u'admin', u'fromgod1')), id=1)], fullname=None, id=4, name=u'shg36dpgdz')

In [19]: Domain(id=4).delete()

Out[19]:
{u'created_at': u'2015-05-29T00:10:46Z',
 u'dns_id': 1,
 u'fullname': None,
 u'hostgroups_count': 0,
 u'hosts_count': 0,
 u'id': 4,
 u'name': u'shg36dpgdz',
 u'updated_at': u'2015-05-29T00:10:46Z'}
```

### CODE REVIEW

**Comment by omaciel** [comment]
This fixes #93

**Comment by sthirugn** [comment]
ACK

**Comment by elyezer** [comment]
Why not use `OneToOneField`?

**Comment by omaciel** [comment]
@elyezer the server does not return a hash for that field but a single value: the `id` for a `SmartProxy`. Here's what the server returns:

```json
{u'created_at': u'2015-05-28T16:17:22Z',
 u'dns_id': 1,
 u'fullname': None,
 u'id': 1,
 u'interfaces': [],
 u'locations': [{u'id': 2,
   u'name': u'Default Location',
   u'title': u'Default Location'}],
 u'name': u'lab.eng.rdu2.redhat.com',
 u'organizations': [{u'id': 1,
   u'name': u'Default Organization',
   u'title': u'Default Organization'}],
 u'parameters': [],
 u'subnets': [{u'id': 1,
   u'name': u'libvirt_subnet',
   u'network_address': u'192.168.100.0/24'}],
 u'updated_at': u'2015-05-28T20:48:13Z'}
```

Since the `dns_id`` field is not required, I guess we don't have to worry about having it automatically generated for us, but I wonder if we want to add logic to the creation/reading methods so that if a `SmartProxy` object is passed, then it should use the object's `id` only **or** is we should leave things as they are and make sure that the (integer) `id` value is what is required if using that field?

**Comment by Ichimonji10** [comment]
Unfortunately, the server is very inconsistent about whether it returns a hash of information about a referenced entity or just an ID or list of IDs. This sometimes leads to some pretty epic hacking around. Check out `HostGroup.read`:

```
        Normalize the data received from the server.

        The server returns data in this format::

            {
                'id': 15,
                'name': 'name',
                'title': 'title',
                'subnet_id': null,
                'subnet_name': null,
                'operatingsystem_id': null,
                'operatingsystem_name': null,
                …
            }

        Normalize data to this format::

            {
                'id': 15,
                'name': 'name',
                'title': 'title',
                'subnet': {'id': …},
                'operatingsystem': {'id': …},
                …
            }
```

The current solution is to deal with these inconsistencies on a case-by-case basis. Here's a pretty typical example of how to do that:

```python
    def read(self, entity=None, attrs=None, ignore=()):
        """Compensate for the weird structure of returned data."""
        if attrs is None:
            attrs = self.read_json()
        # The server returns an ID for this attr instead of a dict of data.
        gpg_key_id = attrs.pop('gpg_key_id')
        if gpg_key_id is None:
            attrs['gpg_key'] = None
        else:
            attrs['gpg_key'] = {'id': gpg_key_id}
        return super(Repository, self).read(entity, attrs, ignore)
```

Writing boilerplate code like this all over the place sucks, of course. A nice enhancement would be to add logic in to the `EntityReadMixin.read` method that would deal with cases like this.

Anyway, what should be done? Declare a `OneToOneField`:

```python
'dns_id': entity_fields.OneToOneField(SmartProxy),
```

And then add in whatever logic is necessary to make `create()` and `read()` both work correctly. You can test the `read()` method by adding several lines to `ReadTestCase.test_attrs_arg_v1` and `ReadTestCase.test_entity_ids`. There are currently no unit tests for the `create()` methods.

**Comment by elyezer** [comment]
:+1: on adding the workaround.

**Comment by Ichimonji10** [comment]
I'm putting together a commit that implements this workaround right now.

**Comment by Ichimonji10** [comment]
Superceded by #99.

**Pull request closed without merging**
