### PR TITLE
Add SearchMixin for SyncPlan entity

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by omaciel** [comment]
@ehelms can we get some tests or sample code showing off that this works as expected?

**Comment by elyezer** [comment]
I did a simple test and it is working:

```
In [6]: SyncPlan(organization=1).search()
2016-04-28 09:12:29 - nailgun.client - DEBUG - Making HTTP GET request to https://sat.example.com:443/katello/api/v2/organizations/1/sync_plans with options {'data': '{"organization_id": 1}', 'headers': {'content-type': 'application/json'}, 'auth': ('admin', 'changeme'), 'verify': False} and no data.
2016-04-28 09:12:30 - nailgun.client - DEBUG - Received HTTP 200 response: {"total":0,"subtotal":0,"page":1,"per_page":20,"error":null,"search":null,"sort":{"by":null,"order":null},"results":[]}
```

**Comment by omaciel** [comment]
ACK

**Comment by Ichimonji10** [comment]
:+1:

**Comment by elyezer** [comment]
ACK

**Pull request merged**
