### PR TITLE
Change dependencies

### LINKED ISSUE #144: Use "packaging" as a dependency
The [packaging](https://packaging.pypa.io/en/latest/) library a set of "core utilities for Python packages." One of the things it provides is a set of tools for parsing and comparing versions. The package is provided by the Python Packaging Authority.

The "setuptools" package also provides the ability to parse and compare versions. However, a look at the source code shows that setuptools simply depends on packaging and wraps what packaging provides.

packaging is a more targeted and specific tool. NailGun only uses the versioning capabilities from setuptools, and it seems reasonable for NailGun to make use of a more targeted dependency.

This is a breaking change for the following reasons:

* We're changing dependencies.
* Clients that hook tightly in to NailGun may make use of `pkg_resources.parse_version` and `pkg_resources.SetuptoolsVersion`. (Not sure why, but hey.)

### PR DESCRIPTION
**Pull request by Ichimonji10**
Fix #144. Drop "setuptools" as a dependency and use "packaging" instead.

### CODE REVIEW

**Comment by Ichimonji10** [comment]
Robottelo does not reference pkg_resources anywhere, so this PR should not affect Robottelo in any way.

Anyone who is using NailGun directly instead of installing via PyPi will need to do `pip install -r requirements.txt`. @kbidarkar @sthirugn

**Comment by oshtaier** [comment]
ACK

**Comment by JacobCallahan** [comment]
ACK

**Comment by elyezer** [comment]
:+1:

**Pull request merged**
