### PR TITLE
Add nailgun support for RHCloud Inventory API

### PR DESCRIPTION
**Pull request by jameerpathan111**
##### Description of changes

This PR adds nailgun support for RHCloud Inventory API.

##### Upstream PR link

https://github.com/theforeman/foreman_rh_cloud/pull/572

##### Functional demonstration

```
In [2]: generate_report = entities.RHCloud(organization_id=1).generate_report()                                                                                           

In [3]: generate_report                                                                                                                                                   
Out[3]: {'action_status': 'success'}

In [6]: download_report = entities.RHCloud(organization_id=1).download_report(destination='/home/jpathan/Downloads/org_1.tar.xz')                                         

In [8]: sync_inventory = entities.RHCloud(organization_id=1).inventory_sync()                                                                                             

In [9]: sync_inventory                                                                                                                                                    
Out[9]: 
{'task': {'id': '85cd861a-b4ba-4e85-bebf-842bee26a288',
  'label': 'InventorySync::Async::InventoryFullSync',
  'started_at': '2021-10-26T10:28:42.861Z',
  'ended_at': None,
  'state': 'planned',
  'result': 'pending',
  'external_id': '0d1a6b3a-d0ee-4c4c-b55f-07b94e5d2e03',
  'parent_task_id': None,
  'start_at': '2021-10-26T10:28:42.847Z',
  'start_before': None,
  'action': 'Inventory full sync',
  'user_id': 4,
  'state_updated_at': '2021-10-26T10:28:42.903Z'}}

```

### CODE REVIEW

**Comment by jameerpathan111** [comment]
@jyejare @mshriver I have update the PR.

**Comment by jameerpathan111** [comment]
Note: Code check is not running for nailgun, not sure what the root cause is.

**Review by mshriver — APPROVED** [review]

**Comment by jyejare** [comment]
@jameerpathan111 The checks are not passing because there are no checks at all 🤣 

I am opening a ticket to implement it! @JacobCallahan What should we until then with these PRs ?

**Comment by JacobCallahan** [comment]
Nailgun tests can be ran locally with results put in a comment.

**Comment by jyejare** [comment]
@JacobCallahan Perfect !

@jameerpathan111 Please run the test locally using `Make`, refer to https://github.com/SatelliteQE/nailgun/blob/master/.travis.yml in that `-script` section to understand what checks you should run!

**Comment by jameerpathan111** [comment]
@jyejare @JacobCallahan ran tests locally using `make test-coverage`.
```
(env-nailgun) [jpathan@jpathan nailgun]$ make test-coverage
coverage run --source nailgun -m unittest discover --start-directory tests --top-level-directory .
.....................................................................................................................................................................................................................................................................
----------------------------------------------------------------------
Ran 261 tests in 6.901s

OK

```

**Comment by jyejare** [comment]
@jameerpathan111 Please run all the checks! 

@JacobCallahan This is where I want to introduce local checks run using https://github.com/nektos/act and there are other advantages as well which we discussed in a meeting once.

**Comment by jameerpathan111** [comment]
@jyejare @JacobCallahan 
```

(env-nailgun) [jpathan@jpathan nailgun]$ pre-commit run --all-files
Reorder python imports...................................................Passed
pyupgrade................................................................Passed
black....................................................................Passed
Trim Trailing Whitespace.................................................Passed
Fix End of Files.........................................................Passed
Check Yaml...............................................................Passed
Debug Statements (Python)................................................Passed

(env-nailgun) [jpathan@jpathan nailgun]$ flake8

(env-nailgun) [jpathan@jpathan nailgun]$ make test-coverage
coverage run --source nailgun -m unittest discover --start-directory tests --top-level-directory .
.....................................................................................................................................................................................................................................................................
----------------------------------------------------------------------
Ran 261 tests in 6.933s

OK

(env-nailgun) [jpathan@jpathan nailgun]$ make docs-html
make[1]: Entering directory `/home/jpathan/projects/nailgun/docs'
sphinx-build -b html -d _build/doctrees  -W . _build/html
Running Sphinx v2.2.0
making output directory... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 15 source files that are out of date
updating environment: [new config] 15 added, 0 changed, 0 removed
reading sources... [100%] index                                                                                                                                           
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] index                                                                                                                                            
generating indices...  genindex py-modindexdone
writing additional pages...  searchdone
copying static files... ... done
copying extra files... done
dumping search index in English (code: en)... done
dumping object inventory... done
build succeeded.

The HTML pages are in _build/html.

Build finished. The HTML pages are in _build/html.
make[1]: Leaving directory `/home/jpathan/projects/nailgun/docs'
(env-nailgun) [jpathan@jpathan nailgun]$ make docs-clean
make[1]: Entering directory `/home/jpathan/projects/nailgun/docs'
rm -rf _build/*
make[1]: Leaving directory `/home/jpathan/projects/nailgun/docs'

(env-nailgun) [jpathan@jpathan nailgun]$ make package
./setup.py sdist bdist_wheel --universal
running sdist
running egg_info
creating nailgun.egg-info
writing nailgun.egg-info/PKG-INFO
writing dependency_links to nailgun.egg-info/dependency_links.txt
writing requirements to nailgun.egg-info/requires.txt
writing top-level names to nailgun.egg-info/top_level.txt
writing manifest file 'nailgun.egg-info/SOURCES.txt'
reading manifest file 'nailgun.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'nailgun.egg-info/SOURCES.txt'
running check
creating nailgun-0.32.0
creating nailgun-0.32.0/nailgun
creating nailgun-0.32.0/nailgun.egg-info
copying files to nailgun-0.32.0...
copying MANIFEST.in -> nailgun-0.32.0
copying README.rst -> nailgun-0.32.0
copying VERSION -> nailgun-0.32.0
copying setup.py -> nailgun-0.32.0
copying nailgun/__init__.py -> nailgun-0.32.0/nailgun
copying nailgun/client.py -> nailgun-0.32.0/nailgun
copying nailgun/config.py -> nailgun-0.32.0/nailgun
copying nailgun/entities.py -> nailgun-0.32.0/nailgun
copying nailgun/entity_fields.py -> nailgun-0.32.0/nailgun
copying nailgun/entity_mixins.py -> nailgun-0.32.0/nailgun
copying nailgun.egg-info/PKG-INFO -> nailgun-0.32.0/nailgun.egg-info
copying nailgun.egg-info/SOURCES.txt -> nailgun-0.32.0/nailgun.egg-info
copying nailgun.egg-info/dependency_links.txt -> nailgun-0.32.0/nailgun.egg-info
copying nailgun.egg-info/requires.txt -> nailgun-0.32.0/nailgun.egg-info
copying nailgun.egg-info/top_level.txt -> nailgun-0.32.0/nailgun.egg-info
Writing nailgun-0.32.0/setup.cfg
creating dist
Creating tar archive
removing 'nailgun-0.32.0' (and everything under it)
running bdist_wheel
running build
running build_py
creating build
creating build/lib
creating build/lib/nailgun
copying nailgun/entities.py -> build/lib/nailgun
copying nailgun/client.py -> build/lib/nailgun
copying nailgun/entity_mixins.py -> build/lib/nailgun
copying nailgun/config.py -> build/lib/nailgun
copying nailgun/__init__.py -> build/lib/nailgun
copying nailgun/entity_fields.py -> build/lib/nailgun
installing to build/bdist.linux-x86_64/wheel
running install
running install_lib
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/wheel
creating build/bdist.linux-x86_64/wheel/nailgun
copying build/lib/nailgun/entities.py -> build/bdist.linux-x86_64/wheel/nailgun
copying build/lib/nailgun/client.py -> build/bdist.linux-x86_64/wheel/nailgun
copying build/lib/nailgun/entity_mixins.py -> build/bdist.linux-x86_64/wheel/nailgun
copying build/lib/nailgun/config.py -> build/bdist.linux-x86_64/wheel/nailgun
copying build/lib/nailgun/__init__.py -> build/bdist.linux-x86_64/wheel/nailgun
copying build/lib/nailgun/entity_fields.py -> build/bdist.linux-x86_64/wheel/nailgun
running install_egg_info
Copying nailgun.egg-info to build/bdist.linux-x86_64/wheel/nailgun-0.32.0-py3.6.egg-info
running install_scripts
adding license file "LICENSE" (matched pattern "LICEN[CS]E*")
creating build/bdist.linux-x86_64/wheel/nailgun-0.32.0.dist-info/WHEEL
creating 'dist/nailgun-0.32.0-py2.py3-none-any.whl' and adding 'build/bdist.linux-x86_64/wheel' to it
adding 'nailgun/__init__.py'
adding 'nailgun/client.py'
adding 'nailgun/config.py'
adding 'nailgun/entities.py'
adding 'nailgun/entity_fields.py'
adding 'nailgun/entity_mixins.py'
adding 'nailgun-0.32.0.dist-info/LICENSE'
adding 'nailgun-0.32.0.dist-info/METADATA'
adding 'nailgun-0.32.0.dist-info/WHEEL'
adding 'nailgun-0.32.0.dist-info/top_level.txt'
adding 'nailgun-0.32.0.dist-info/RECORD'
removing build/bdist.linux-x86_64/wheel

(env-nailgun) [jpathan@jpathan nailgun]$ make package-clean
rm -rf build dist nailgun.egg-info

```

**Review by jyejare — APPROVED** [review]

**Pull request merged**
