### PR TITLE
Add json response to entity creation error message

### PR DESCRIPTION
**Pull request by dosas**
##### Description of changes

Add json response to entity creation error message

* Makes the error message information more detailed and informative
* Possibility to write more precise assertions

There are some robottelo tests that would greatly benefit from more precise assertions on error messages, i.e.
[tests/foreman/api/test_repository.py::TestRepository::test_negative_update_checksum_with_on_demand_policy](https://github.com/SatelliteQE/robottelo/blob/master/tests/foreman/api/test_repository.py#L532) (or other tests in this module)
I doubt that the supposed error message should be:
```
RuntimeError: The repository's publication is missing. Please run a 'complete sync' on MPvytWJ.","errors":["Task c7fa616b-2f71-4476-b581-1cae65a9eafd: RuntimeError: The repository's publication is missing. Please run a 'complete sync' on MPvytWJ."]}
```

##### Upstream API documentation, plugin, or feature links

None

##### Functional demonstration

Example:

before:
```
requests.exceptions.HTTPError: ('422 Client Error: Unprocessable Content for url: https://robottelo...')
```

after
```
requests.exceptions.HTTPError: ('422 Client Error: Unprocessable Content for url: https://...', {'displayMessage': 'Validation failed: When "Upstream URL" is set, "Releases/Distributions" must also be set!', 'errors': {'base': ['When "Upstream URL" is set, "Releases/Distributions" must also be set!']}}
```

##### Additional Information

None

### CODE REVIEW

**Comment by omkarkhatavkar** [comment]
trigger: test-robottelo
pytest: -k test_negative_update_checksum_with_on_demand_policy tests/foreman/api/test_repository.py

**Review by omkarkhatavkar — APPROVED** [review]
Nice Addition @dosas

**Comment by Satellite-QE** [comment]
**PRT Result**
```
Build Number: 25
Build Status: SUCCESS
PRT Comment: pytest -k test_negative_update_checksum_with_on_demand_policy tests/foreman/api/test_repository.py --external-logging
Test Result : ========== 2 passed, 163 deselected, 23 warnings in 715.00s (0:11:54) ==========
```

**Comment by dosas** [comment]
@omkarkhatavkar I sadly cannot set the labels.

Do we need additional reviewers?

**Comment by omkarkhatavkar** [comment]
@JacobCallahan @jyejare @ogajduse  Looks an interesting PR. We need more review to merge this.

**Review by JacobCallahan — APPROVED** [review]
ACK on the changes. However, @dosas are there any existing tests (in robottelo) that this change would impact?

**Comment by dosas** [comment]
> ACK on the changes. However, @dosas are there any existing tests (in robottelo) that this change would impact?

This should not affect the robottelo tests. The tests I have seen so far only check for `requests.exceptions.HTTPError` and not the content of the error message .

**Pull request merged**
