### PR TITLE
Fixing sync plan update_payload to update only specific field

### PR DESCRIPTION
**Pull request by oshtaier**
Just an example that fix is working
```
for i in {1..10}; do py.test tests/foreman/api/test_syncplan.py -k test_positive_update_interval; done
=========================================================================== test session starts ============================================================================
platform linux2 -- Python 2.7.5, pytest-2.8.1, py-1.4.30, pluggy-0.3.1
rootdir: /home/oshtaier/Desktop/robottelo, inifile: 
collected 30 items 

tests/foreman/api/test_syncplan.py .

========================================================= 29 tests deselected by '-ktest_positive_update_interval' =========================================================
================================================================= 1 passed, 29 deselected in 12.65 seconds =================================================================
=========================================================================== test session starts ============================================================================
platform linux2 -- Python 2.7.5, pytest-2.8.1, py-1.4.30, pluggy-0.3.1
rootdir: /home/oshtaier/Desktop/robottelo, inifile: 
collected 30 items 

tests/foreman/api/test_syncplan.py .

========================================================= 29 tests deselected by '-ktest_positive_update_interval' =========================================================
================================================================= 1 passed, 29 deselected in 12.94 seconds =================================================================
=========================================================================== test session starts ============================================================================
platform linux2 -- Python 2.7.5, pytest-2.8.1, py-1.4.30, pluggy-0.3.1
rootdir: /home/oshtaier/Desktop/robottelo, inifile: 
collected 30 items 

tests/foreman/api/test_syncplan.py .

========================================================= 29 tests deselected by '-ktest_positive_update_interval' =========================================================
================================================================= 1 passed, 29 deselected in 12.63 seconds =================================================================
=========================================================================== test session starts ============================================================================
platform linux2 -- Python 2.7.5, pytest-2.8.1, py-1.4.30, pluggy-0.3.1
rootdir: /home/oshtaier/Desktop/robottelo, inifile: 
collected 30 items 

tests/foreman/api/test_syncplan.py .

========================================================= 29 tests deselected by '-ktest_positive_update_interval' =========================================================
================================================================= 1 passed, 29 deselected in 12.79 seconds =================================================================
=========================================================================== test session starts ============================================================================
platform linux2 -- Python 2.7.5, pytest-2.8.1, py-1.4.30, pluggy-0.3.1
rootdir: /home/oshtaier/Desktop/robottelo, inifile: 
collected 30 items 

tests/foreman/api/test_syncplan.py .

========================================================= 29 tests deselected by '-ktest_positive_update_interval' =========================================================
================================================================= 1 passed, 29 deselected in 13.94 seconds =================================================================
=========================================================================== test session starts ============================================================================
platform linux2 -- Python 2.7.5, pytest-2.8.1, py-1.4.30, pluggy-0.3.1
rootdir: /home/oshtaier/Desktop/robottelo, inifile: 
collected 30 items 

tests/foreman/api/test_syncplan.py .

========================================================= 29 tests deselected by '-ktest_positive_update_interval' =========================================================
================================================================= 1 passed, 29 deselected in 13.03 seconds =================================================================
=========================================================================== test session starts ============================================================================
platform linux2 -- Python 2.7.5, pytest-2.8.1, py-1.4.30, pluggy-0.3.1
rootdir: /home/oshtaier/Desktop/robottelo, inifile: 
collected 30 items 

tests/foreman/api/test_syncplan.py .

========================================================= 29 tests deselected by '-ktest_positive_update_interval' =========================================================
================================================================= 1 passed, 29 deselected in 12.78 seconds =================================================================
=========================================================================== test session starts ============================================================================
platform linux2 -- Python 2.7.5, pytest-2.8.1, py-1.4.30, pluggy-0.3.1
rootdir: /home/oshtaier/Desktop/robottelo, inifile: 
collected 30 items 

tests/foreman/api/test_syncplan.py .

========================================================= 29 tests deselected by '-ktest_positive_update_interval' =========================================================
================================================================= 1 passed, 29 deselected in 13.04 seconds =================================================================
=========================================================================== test session starts ============================================================================
platform linux2 -- Python 2.7.5, pytest-2.8.1, py-1.4.30, pluggy-0.3.1
rootdir: /home/oshtaier/Desktop/robottelo, inifile: 
collected 30 items 

tests/foreman/api/test_syncplan.py .

========================================================= 29 tests deselected by '-ktest_positive_update_interval' =========================================================
================================================================= 1 passed, 29 deselected in 12.72 seconds =================================================================
=========================================================================== test session starts ============================================================================
platform linux2 -- Python 2.7.5, pytest-2.8.1, py-1.4.30, pluggy-0.3.1
rootdir: /home/oshtaier/Desktop/robottelo, inifile: 
collected 30 items 

tests/foreman/api/test_syncplan.py .

========================================================= 29 tests deselected by '-ktest_positive_update_interval' =========================================================
================================================================= 1 passed, 29 deselected in 16.23 seconds =================================================================
```

### CODE REVIEW

**Comment by abalakh** [comment]
Short explanation - we have some random failures due to inconsistency in accepted and returned sync date format. Before this fix on each update operation all the fields were passed, making tests which are not related to sync date check fail. With this fix for example `sync_plan.update(['interval'])` will update only interval and won't pass sync date which may be broken, and test results are just a proof those failures are gone.

**Comment by abalakh** [comment]
ACK

**Comment by sthirugn** [comment]
awesome great work catching this.

**Comment by sthirugn** [comment]
ACK

**Pull request merged**
